### ISSUE TITLE
How would I load a premade playlist from jwPlayer?

### ISSUE THREAD

**Issue by et-nat1995** [chaimPaneth/react-native-jw-media-player#100]
Hey there,

I am trying to build a react native app to be able to pull videos from jwPlayer and some of videos are structured as a main video in a playlist and supplement videos breaking down each section in the main video.

I am able to get regular videos following this structure: 
```
 const playlistItem = {
    title: 'Track',
    mediaId: 'mediaId',
    desc: 'My beautiful track',
    time: 0,
    file: `https://content.jwplatform.com/videos/mediaID.mp3`,
    autostart: false,
    controls: true,
    repeat: false,
    displayDescription: true,
    displayTitle: false,
  }
```

How would I go about getting video that are returned from jwPlayer playlist and to show the playlist icon?
For example: `https://content.jwplatform.com/feeds/Playlist_ID.json`

**Comment by chaimPaneth** [comment]
Hi @et-nat1995 I think this url should give you playlist data https://cdn.jwplayer.com/v2/media/id, this should work for playlists, live events, video etc all media.

Hope that helps.
