### ISSUE TITLE
[android] loadPlaylistItem() set new audio and controls in the media center.

### ISSUE THREAD

**Issue by Infokora** [chaimPaneth/react-native-jw-media-player#102]
Hi everyone. After i set new audio, player start playing, but don`t will stop prev audio, and all new/next audio will overlaps each other, and sound together. 
Controls in the android media center, control only first audio and don`t work with new audio.

**Comment by fvasyliuk** [comment]
me helped:
add "this.destroyPlayer();"  in RNJWPlayerView -> setupPlayerWithFirstItem before "mPlayer = new RNJWPlayer(simpleContext, playerConfig);"

**Comment by chaimPaneth** [comment]
Hi @Infokora @fvasyliuk I released version 0.1.53 with the suggested fix.

Thank you.
