### ISSUE TITLE
Local Media Playback

### ISSUE THREAD

**Issue by arsimr16** [chaimPaneth/react-native-jw-media-player#106]
I'm trying to figure out if this package supports local media playback.  I want to loop a short mp4 file in the background of the logged out welcome screen.

It seems like the Android and iOS SDKs both support local media playback.  The documentation can be found here:
[Android](https://developer.jwplayer.com/jwplayer/docs/android-configure-local-media-playback) 
[iOS](https://developer.jwplayer.com/jwplayer/docs/ios-embedding#section-local-file-playback)

I know the `file` prop works with urls, but I was wondering if it could also work with the `file:/// protocol` mentioned in the Android SDK documentation or the `file:// protocol` mentioned in the iOS SDK documentation.  (As far as I can tell these protocols are the same and the third forward slash in the Android one is just the root directory - [see this stackoverflow post](https://stackoverflow.com/questions/3616795/what-is-the-difference-between-file-file-file))

I tried getting this to work on Android and iOS and did not have any success.  I tried putting the `.mp4` file in the react native project root directory, the root of the android and ios directories, and the root of the directory with all my `.js` files.  I tried every combination of this `file://` protocol I could think of (with and without the file extension, with and without `file://`, with 2 forward slashes, with 3 forward slashes) and still had no luck.  I even tried downloading another sample `.mp4` file to make sure a bad file wasn't the cause of this problem.

On iOS, the spinner that shows when the video is buffering just spins forever.  On Android, I do get an error message `303200` (https://developer.jwplayer.com/jwplayer/docs/jw8-player-errors-reference) which unhelpfully means 'The play attempt failed for unknown reasons'.  I tried changing the path to a made-up filename and got the same error.

Am I doing something wrong (maybe the file has to be in a certain directory that I didn't try, or maybe I'm messing up the `file://` path somehow), or does something need to be added to this package that would hook into the native SDKs?  Any insight I could get on this would be much appreciated.  I tried looking at the native code, but I really don't understand how it works.  For now I can work around this by hosting the video and using a url.

**Comment by chaimPaneth** [comment]
Hi @arsimr16 

Local files do work with this library we use it local files a lot.

We use react-native-fs to get the file path and pass that in the file prop

```
import RNFS from "react-native-fs";

const filePath = "path to where your local file is, perhaps in RNFS.DocumentDirectoryPath"
return (await RNFS.exists(filePath)) ? "file://" + filePath : false;
```

Tell me if this works for you,
Thanks

**Comment by arsimr16** [comment]
Thank you!  This works for me :)
