### ISSUE TITLE
[android] How to change item in a playlist?

### ISSUE THREAD

**Issue by fvasyliuk** [chaimPaneth/react-native-jw-media-player#113]
Hello!
I am integrating this into my project and running into an issue. The issue is that I can't change track in a playlist for android.
For ios I use setPlaylistIndex but for android, it's don't work.

Any ideas on what I might be doing wrong? Any information I can provide you to help debug this?

Thanks!

**Comment by fvasyliuk** [comment]
me helped:
change "playerView.mPlayer.setCurrentAudioTrack(index);" to "playerView.mPlayer.playlistItem(index);" in RNJWPlayerModule.java -> setPlaylistIndex

**Comment by chaimPaneth** [comment]
Hi @fvasyliuk 

I've pushed this change in version 0.1.54 can you check if it's working for you now.

Thank you.
