### ISSUE TITLE
How to get current playlist item?

### ISSUE THREAD

**Issue by marcinkieruzel** [chaimPaneth/react-native-jw-media-player#119]
Is there a way to get current playing item programmatically? For example on onPlaylistItem callback?
I'm trying to build my own player view - with callbacks.

**Comment by chaimPaneth** [comment]
@marcinkieruzel Yes onPlaylistItem callback is a good place to get the current playing item and index does this work for you?

**Comment by marcinkieruzel** [comment]
@chaimPaneth yes thank you - I forgot to use nativeEvent
