### ISSUE TITLE
Try to run local storage path in ios in react-native-jw-player

### ISSUE THREAD

**Issue by Rishabh6211** [chaimPaneth/react-native-jw-media-player#128]
I am trying to run the code using xcode with Simulator(iphone 11 pro).

I have done the all setup of React-Native-Jw-Player with pod and added the key and sdk as well

Issue - i am trying to play the video file from the local path of the simulator using ios in jw player but it's not reading the path - 

file:'/Users/rishabh/Library/Developer/CoreSimulator/Devices/C20205E8-CCCD-4583-834F-87FA0420E4EB/data/Containers/Data/Application/F7317413-87CD-4EE2-9B96-4DAB807CFF2E/Documents/chunklist_w79586375.m3u8'

"or"

file:'file:///Users/rishabh/Library/Developer/CoreSimulator/Devices/C20205E8-CCCD-4583-834F-87FA0420E4EB/data/Containers/Data/Application/F7317413-87CD-4EE2-9B96-4DAB807CFF2E/Documents/chunklist_w79586375.m3u8'

Here is my code

                            ``` <JWPlayer
                                style={styles.player}
                                playlistItem={{
                                    title: 'Track',                                 
                                    mediaId: '1',
                                   file:'/Users/rishabh/Library/Developer/CoreSimulator/Devices/C20205E8-CCCD-4583-834F-87FA0420E4EB/data/Containers/Data/Application/F7317413-87CD-4EE2-9B96-4DAB807CFF2E/Documents/chunklist_w79586375.m3u8',
                                    autostart: false,
                                    
                                }}
                                
                                onBeforePlay={(data) => this.onBeforePlay(data)}
                                onPlay={() => this.onPlay()}
                                onSetupPlayerError={(e) => this.onSetupPlayerError(e)}
                                onPlayerError={(e) => this.onPlayerError(e)}
                                onBuffer={(e) => this.onBuffer(e)}
                                onTime={(time) => this.onTime(time)}
                                nativeFullScreen={true} // when undefined or false you will need to handle the player styles in onFullScreen & onFullScreenExit callbacks
                                onFullScreen={() => this.onFullScreen()}
                                onFullScreenExit={() => this.onFullScreenExit()}
                            />```

**Comment by archcorsair** [comment]
I believe you cannot use a static path like that. Have you tried to import it first?

**Comment by Rishabh6211** [comment]
Yeah @archcorsair I tried with that as well i created the video folder inside of my project and then import it but its not working

**Comment by archcorsair** [comment]
@Rishabh6211 Have you tried playing an mp4 file? I just noticed you're trying to import an m3u8 which might point to media that doesn't exist or is not accessible.

**Comment by chaimPaneth** [comment]
Hi @Rishabh6211 

I use react-native-fs to locate the actual file path and then append to the path file:// + path

**Comment by Rishabh6211** [comment]
Hi @archcorsair Yeah i tried playing mp4 as well but not working .
Hi @chaimPaneth  i used rect-native-fs as well

**Comment by arsimr16** [comment]
This is what worked for me:

Save video here for Android: `android/app/scr/main/assets/video.mp4`
Save video here for iOS: `ios/video.mp4`

```
import RNFS from 'react-native-fs';

file path for Android: 'file:///android_asset/video.mp4'
file path for iOS: `file://${RNFS.MainBundlePath}/video.mp4`
```

**Comment by puneetkansal04** [comment]
@arsimr16  This is not worked for me

**Comment by puneetkansal04** [comment]
@arsimr16 i want to download .m3u8 playlist locally then i have to play it. So please let me know if you have idea to make it.

**Comment by Rishabh6211** [comment]
@puneetkansal04  I used two lib for download the m3u8 file ,
Rnfs and React native background downloader

**Comment by puneetkansal04** [comment]
@Rishabh6211 okay i will try with it. But at this time i am having a folder and i am giving it's location m3u8 location. But it is not playing video from local folder.

**Comment by puneetkansal04** [comment]
@Rishabh6211 as i am able to check with this server i can access folder from my project bundle. But the thing is i want to download videos in the app like. So multiple videos in the app on mobile storage. So i have to access that from the storage location and play it. How will i do this?

**Comment by Rishabh6211** [comment]
Yeah I already suggested that you can easily download multiple file in loop using that lib.
Rnfs and React native background downloader.
If you faced any issues you can wtsapp me 8707025813.
Hope I will help you.

**Comment by chaimPaneth** [comment]
I've added a local file example in the example project.
