### ISSUE TITLE
Background audio does not work in ios.

### ISSUE THREAD

**Issue by krupalikevadiya** [chaimPaneth/react-native-jw-media-player#136]
I also added code into appdelegate.m as per guide and also added backgroundAudioEnabled in playlistItem.Here i attach my code please guide me to play audio in background. 

  <JWPlayer
              style={styles.player}
              playlistItem={{
                mediaId: "1",
                file: "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8",
                autostart: false,
                backgroundAudioEnabled: true
              }}
              onBeforePlay={() => this.onBeforePlay()}
              onPlay={() => this.onPlay()}
              onSetupPlayerError={(e) => this.onSetupPlayerError(e)}
              onPlayerError={(e) => this.onPlayerError(e)}
              onBuffer={() => this.onBuffer()}
              onTime={(time) => this.onTime(time)}
              nativeFullScreen={true} // when undefined or false you will need to handle the player styles in onFullScreen & onFullScreenExit callbacks
              onFullScreen={() => this.onFullScreen()}
              onFullScreenExit={() => this.onFullScreenExit()}
            />

**Comment by chaimPaneth** [comment]
Hi @krupalikevadiya 

Did you add `Audio` in `Background Modes` under `Signing & Capabilities`

**Comment by krupalikevadiya** [comment]
Yes it is solved thanks for reply.
