### ISSUE TITLE
IOS One Player instance already working and add other JWPlayer with autostart: true  , but Not playing from second player

### ISSUE THREAD

**Issue by Depthol93** [chaimPaneth/react-native-jw-media-player#141]
Hello , I need 2 instance of JWPlayer . One is Playing proper with autostart: true  , but add other JWPlayer with autostart: true not playing , That player's onPlayerReady onBeforePlay  both methods get called but onPlay was not called and Also not playing Sound for 2nd player. 
If I start both player at same time it is Playing properly. But if Start one and second after that Second player is not playing any sound at all. How can I fix this please help.

**Comment by chaimPaneth** [comment]
Hi @Depthol93 

Can you try with the latest version of the lib and lemme know.

Thanks,
Chaim
