### ISSUE TITLE
Unable to play all video using JW player

### ISSUE THREAD

**Issue by saurabh-nandan** [chaimPaneth/react-native-jw-media-player#143]
I am using JW player for playing offline video in react Native app. I have stored video file in device storage and created a static server using react-native-static-server. while i am trying to play video using the player only first video is being played rest of all are not. next time when i reload the app then only one video is playing next is loading for infinite time. Is it storing some cache for playing video ? I am stuck here. Please give me a clue.

Thanks.

![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 21 26 32](https://user-images.githubusercontent.com/47634223/120354461-109c9880-c320-11eb-8a6d-3feddc71c858.png)
![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 21 24 52](https://user-images.githubusercontent.com/47634223/120354181-ddf2a000-c31f-11eb-9a39-dd0f09e236ac.png)
![Simulator Screen Shot - iPhone 12 - 2021-06-01 at 21 25 13](https://user-images.githubusercontent.com/47634223/120354197-e054fa00-c31f-11eb-962c-0ce8ac40e638.png)

**Comment by chaimPaneth** [comment]
Hi @saurabh-nandan , @vyomGupta736,

Can you guys try with the latest version I've also added in the example app a list with players to test this use case.

Thanks,
Chaim
