### ISSUE TITLE
Player pauses when app goes into background

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#147]
Currently using the latest version "react-native-jw-media-player": "^0.1.57",
Using only on Android. I don't have iOS phone on my hand to test that on iOS.

I found this issue that if "autoPlay" is set to TRUE and no user action is required to play the video the player will pause once app goes into the background (home button). But if "autoPlay" is set to FALSE and user has to manually press PLAY button then video continues to play even if in the background.

Expected behavior:
1. Video continues to play even if autoPlay is true.
2. Make this configurable?

**Comment by KestasVenslauskas** [comment]
Also if autoPlay is set to TRUE and user manually pressed PAUSE then PLAY again it also works in background

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

This issue was fixed in latest versions.

Thanks.
