### ISSUE TITLE
interfaceBehaviour prop is not documented

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#160]
interfaceBehaviour has no documentation.
Also it's required by the Config type.
But if you pass anything it gives error even if you pass correct value:  "value was expeted one of the ["0", "1", "2"]"

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

I've updated the readme, but the crash seems to come from the JW SDK itself, I will ask them about this.

**Comment by yksingh12** [comment]
Hi @chaimPaneth , It's working fine when you add this in presentPlayerViewController method after setting the configuration.

 if (configuration != nil) {
    [_playerViewController.player configurePlayerWith:configuration];
    _playerViewController.interfaceBehavior = JWInterfaceBehaviorAlwaysOnScreen;
  }

**Comment by chaimPaneth** [comment]
Hi @yksingh12 

Thank you, your solution works!
I've committed this change and will release it in the coming version.
