### ISSUE TITLE
RNJWPlayerView must implement the OnMetaListener interface!

### ISSUE THREAD

**Issue by felipegmg** [chaimPaneth/react-native-jw-media-player#161]
Hello everybody.
I'm having the issue implementing the component. When assigning the config value and rendering the component, I am getting this error described in the title. As can be seen from the config code, I assigned an empty title value to the first element of the playlist array, as an error was occurring in getTitle as soon as the component was rendered. Having fixed this error (workaround), I'm getting this OnMetaListener error below whenever I try to perform an update in the config field or when trying to unmount the component (the removeListener/removeAllListeners/destroyPlayer methods appears in the error stack):

ps.: The config attribute is inside the state object. 

getTitle Error (setting playlist with empty array)
```
Error while updating property 'config' of a view managed by: RNJWPlayerView

null

Attempt to invoke virtual method 'java.lang.String com.jwplayer.pub.api.media.playlist.PlaylistItem.getTitle()' on a null object reference
```

OnMetaListener error
```
Error while updating property 'config' of a view managed by: RNJWPlayerView

null

RNJWPlayerView must implement the OnMetaListener interface!
```

config code
```
config: {
   license: 'MY LICENSE',
   backgroundAudioEnabled: true,
   fullScreenOnLandscape: true,
   landscapeOnFullScreen: true,
   portraitOnExitFullScreen: true,
   interfaceBehavior: "0",
   styling: {
        colors: {
            timeslider: {
              progress: Palette.primary.replace('#',''),
              thumb: Palette.primary.replace('#',''),
            },
          },
        },
    playlist: [{title: ''}]
}
```

Thanks!

**Comment by chaimPaneth** [comment]
Hi everyone,

This was fixed on latest version 0.2.2.

Thank you so much.
