### ISSUE TITLE
Only First Video is Playing Second Video Not Playing in Android

### ISSUE THREAD

**Issue by SafiDS** [chaimPaneth/react-native-jw-media-player#163]
I followed all the steps while installing.
ios everything works fine but in android, I can't able to play the second video from the list. audio is coming while playing the second video but the video is not working it shows all the black in the video player.

**Comment by bryanhjordan** [comment]
Hey @SafiDS did you fix this?

**Comment by SafiDS** [comment]
@bryanhjordan  No

**Comment by chaimPaneth** [comment]
@SafiDS 

Can you share some of your code for the `<JWPlayer />` also what version of this library are you running?

Thanks
