### ISSUE TITLE
Getting a 'displayDesc is not defined' error when updating to v0.2.2

### ISSUE THREAD

**Issue by et-nat1995** [chaimPaneth/react-native-jw-media-player#165]
<img width="483" alt="Screen Shot 2021-11-01 at 11 21 38 AM" src="https://user-images.githubusercontent.com/42855538/139721544-9aed36c3-abfd-4ade-802d-a9c8612fcb93.png">

My playlist item looks like this:

```
 {
          title: videoTitle ? videoTitle : data.title,
          mediaId: data.mediaid,
          desc: '',
          time: 0,
          file: arrayOfSources.slice(-1)[0].file,
          autostart: false,
          controls: true,
          repeat: false,
          displayDesc: false, // was displayDescription changed to displayDesc and still throws error
          displayTitle: false,
          image: data.images.slice(-1)[0].src
 }
```

JWPlayerKit version -> 4.1.1

**Comment by et-nat1995** [comment]
I think fixing line 425 in index.js in the root directory of this project fixes this issue:
```
displayDescription !== thisConfig.displayDescription ||
```

I'm not sure what this might cause and how this affect the config object or props. In the docs the key is named displayDescription but in this file it's been changes to displayDesc

**Comment by chaimPaneth** [comment]
Hi guys

Your'e right I pushed version 0.2.3 with this fix.

Thank you.

**Comment by et-nat1995** [comment]
Yup no problem! Glad to help!
