### ISSUE TITLE
Video keeps playing when navigated back with react-navigation

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#17]
Platform: Android

When user navigates back from video screen. It keeps playing in background. Also when another video opens during that time app crashes. I also tried unmounting view video is still playing...

**Comment by tkayage** [comment]
I was able to hack by overriding the onDropViewInstance method, then stopping the video:

 @Override
    public void onDropViewInstance(@Nonnull RNJWPlayerView view) {
        super.onDropViewInstance(view);
        mPlayerView.stop();
    }

**Comment by chaimPaneth** [comment]
Thanks @tkayage for the suggestion the latest version implements this and ios is handles too.

**Comment by KestasVenslauskas** [comment]
@chaimPaneth Latest version still doest not contain this fix
