### ISSUE TITLE
AdSchedule Throwing Exception: cannot init a class object

### ISSUE THREAD

**Issue by cheynewallace** [chaimPaneth/react-native-jw-media-player#176]
I've been trying to get the AdSchedule to work (or any ads for that matter) however im getting an instant crash with the following error

```Exception thrown while executing UI block: *** +[JWPlayerKit.JWAdBreak<0x11045bae8> init]: cannot init a class object.```

I've read through all the previous examples and issues and literally copy and pasted apparently working code (from https://github.com/chaimPaneth/react-native-jw-media-player/issues/86), however im unable to load any ads and the player breaks.

My config object

```
	const config: Config = {
		license: xxx
		autostart: true,
		playlist,
		advertising: {
			adClient: "ima",
			adSchedule: [
				{
					tag: "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonly&cmsid=496&vid=short_onecue&correlator=",
					offset: "pre",
				},
			],
		},
	};
```
If I comment out the `advertising` block of the config and reload, it will work again.  

I am using TypeScript and I have noticed that the above config also shows this error, despite it appearing correct to me. There's only 2 attributes so im not sure whats wrong there.

```
Type '{ tag: string; offset: string; }[]' is missing the following properties from type 'AdSchedule': tag, offset ts(2739)
[index.d.ts(34, 5): ]()The expected type comes from property 'adSchedule' which is declared here on type 'Advertising'
```

The full stack trace from the red error that the crash screen shows

```
Exception thrown while executing UI block: *** +[JWPlayerKit.JWAdBreak<0x11045bae8> init]: cannot init a class object.

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1201
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```
We have also tried just using the straight `adVmap` prop and also putting it on the `PlaylistItem` but it does the same. 

This is running the latest version - 0.2.6,  currently only testing this on IOS so I can't confirm if its happening on Android. 

Any ideas @chaimPaneth  ?

**Comment by chaimPaneth** [comment]
Hi @cheynewallace Is this still an issue in the latest versions?

**Comment by cheynewallace** [comment]
Sorry @chaimPaneth we were never able to get this library to work for us so we had to abandon it and build our own solution. 
Feel free to close this issue if you want, I'm not able to test this for you unfortunately.

**Comment by chaimPaneth** [comment]
Closed due to inactivity.
