### ISSUE TITLE
 Ad support

### ISSUE THREAD

**Issue by zikwall** [chaimPaneth/react-native-jw-media-player#18]
Please tell me if there is support for video ads? If so, can you show some code examples?

**Comment by chaimPaneth** [comment]
@zikwall I haven't implemented the necessary callbacks for ad support perhaps this week I'll have time for that.

Thanks

**Comment by j0x0j** [comment]
Hey @chaimPaneth I'm willing to help out on this.

**Comment by ybbond** [comment]
I am eager to see this feature as well.

I have implemented the IMA ads for iOS,

but somehow, following the JWPlayer official docs, it is hard to make ads run on Android

**Comment by wahiche** [comment]
I have a question about ads.  But more about how your plugin works.  It does not ask to choose a specific video player, which in JWPlayer already has the advertisement options built into the specific player.  Instead you are asking for a JW_LICENSE_KEY, which does not choose a specific player from our list.  What player are you using? If not the one on our dashboard?

**Comment by TfADrama** [comment]
> I have a question about ads. But more about how your plugin works. It does not ask to choose a specific video player, which in JWPlayer already has the advertisement options built into the specific player. Instead you are asking for a JW_LICENSE_KEY, which does not choose a specific player from our list. What player are you using? If not the one on our dashboard?

I want to know this too... Any news?

**Comment by dboutin84** [comment]
anybody found solution ?

**Comment by wahiche** [comment]
So I have found a way to actually just use a webview to handle the JWPlayer and get all the adds, the only downfall was that it wont go to fullscreen automatically.  Which I am fine with.  But at least I get the full functionality and the ads.

**Comment by dboutin84** [comment]
are you able to put an auto-play to play ads with webview?

**Comment by wahiche** [comment]
Yes because it is using the web version of the JWPlayer, and those settings are set in the dashboard.  But you need to be able to host that webpage somewhere and do all the setup required there.  I guess you could always inject that info with the injectedJavascript prop that is available with the webview.  I did not do that because we already have a website for our product, so I was able to leverage all the work that was done already.

**Comment by wahiche** [comment]
@dboutin84 if you need any help, or have any questions about how I accomplished it let me know.

**Comment by dboutin84** [comment]
no thank you, i'm ok, i host page with JWplayer and work fine :+1:

**Comment by wahiche** [comment]
That's great.

**Comment by peter7z** [comment]
Hey @wahiche I'm having some trouble setting up a player on a reacct antive webview. Mind giving em a hand?

**Comment by peter7z** [comment]
Hey @ybbond , what did you exactly implement? Im interested, I need adds to play on my react-native app.

**Comment by ybbond** [comment]
> Hey @ybbond , what did you exactly implement? Im interested, I need adds to play on my react-native app.

@peter7z I use Google IMA as advertising provider. I modified this package’s native code directly in the `node_modules`, then use https://github.com/ds300/patch-package to keep the diffs.

Specific to android, I needed to add JWP’s Google IMA package to this packages `build.gradle`:
```implementation 'com.longtailvideo.jwplayer:jwplayer-ima:+'```

Then I just follow the steps to add Advertisement from JWP’s official docs

Hope that gives you some insight!

**Comment by peter7z** [comment]
@ybbond we use IMA too, unluckily I have very little objective-C knowledge. Would you mind sharing some code? If it's not too much trouble, thanks.

**Comment by ybbond** [comment]
@peter7z sure!

add the line that starts with `+` plus sign, the line without it will be the reference where you should add it.

make sure you omit the plus sign! :D

`/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.m`
```ObjectiveC
     config.displayTitle = YES;
     
+    NSArray *tags = @[@"https://blue.kumparan.com/dist/sample-vmap.xml", @"https://blue.kumparan.com/dist/sample-vmap.xml"];
+    JWAdBreak *adBreak = [JWAdBreak adBreakWithTags:tags offset:@"pre"];
+    
+    config.advertising = [JWAdConfig new];
+    config.advertising.client = JWAdClientGoogima;
+    config.advertising.schedule = @[adBreak];
+    config.playbackRateControls = true;
+    

```

**Comment by ybbond** [comment]
@peter7z sure!

add the line that starts with `+` plus sign, the line without it will be the reference where you should add it.

make sure you omit the plus sign! :D

`/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.m`
```ObjectiveC
     config.displayTitle = YES;
     
+    NSArray *tags = @[@"<this is where your vmap/vast xml link should be>"];
+    JWAdBreak *adBreak = [JWAdBreak adBreakWithTags:tags offset:@"pre"];
+    
+    config.advertising = [JWAdConfig new];
+    config.advertising.client = JWAdClientGoogima;
+    config.advertising.schedule = @[adBreak];
+    config.playbackRateControls = true;
+    

```

**Comment by ybbond** [comment]
@peter7z if you better pass your advertisement's xml link as prop, you can do this.

make sure you bridge the props for the android too!

`/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.h`
```ObjectiveC
  @property(nonatomic)BOOL wasInterrupted;
+ // Advertisement ads property. patched
+ @property(nonatomic, strong)NSString *adVmap;
```

`/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.m`
```ObjectiveC
+#import <AVKit/AVKit.h>
+#import <MediaPlayer/MediaPlayer.h>
 NSString* const AudioInterruptionsStarted = @"AudioInterruptionsStarted";
 NSString* const AudioInterruptionsEnded = @"AudioInterruptionsEnded";
 
+@implementation UIViewController (orientationFix)
+-(NSUInteger) supportedInterfaceOrientations
+{
+    if ([[self class] isSubclassOfClass:[AVPlayerViewController class]]) {
+        return UIInterfaceOrientationMaskLandscape;
+    }
+    return UIInterfaceOrientationMaskPortrait;
+}
+- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation
+{
+    if ([[self class] isSubclassOfClass:[AVPlayerViewController class]]) {
+        return UIInterfaceOrientationLandscapeLeft | UIInterfaceOrientationLandscapeRight;
+    }
+    return UIInterfaceOrientationPortrait;
+}
+@end
+
 @implementation RNJWPlayerNativeView
```

still `/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.m`

```ObjectiveC
+-(void)setAdVmap:(NSString *)adVmap
+{
+    if(adVmap != nil && adVmap.length > 0 && ![adVmap isEqualToString:_player.config.advertising.adVmap]) {
+        self.player.config.advertising = [JWAdConfig new];
+        self.player.config.advertising.client = JWAdClientGoogima;
+        self.player.config.advertising.adVmap = adVmap;
+    }
+}
+
+-(NSString *)adVmap
+{
+    return self.player.config.advertising.adVmap;
+}
+
 -(void)setMediaId:(NSString *)mediaId
```

more `/node_modules/react-native-jw-media-player/ios/RNJWPlayerNativeView.m`

```ObjectiveC
+        id adVmap = playlistItem[@"adVmap"];
+        if ((adVmap != nil) && (adVmap != (id)[NSNull null])) {
+            config.advertising = [JWAdConfig new];
+            config.advertising.client = JWAdClientGoogima;
+            config.advertising.adVmap = adVmap;
+        }
+        
         id title = playlistItem[@"title"];
         if ((title != nil) && (title != (id)[NSNull null])) {

```

**Comment by chaimPaneth** [comment]
@ybbond 

Can you create a PR with your code for ad support I'll merge it.

Thanks.

**Comment by ybbond** [comment]
@chaimPaneth thank you for the recognition!

I will make the PR this morning (GMT+7 time).

Actually I am researching and learning to make the ad support as an extension for this package, thus, other people who doesn't need advertisement won't need to download extra package. That plan I'm afraid will take long though.

**Comment by ybbond** [comment]
Hei all, I made the advertisement PR

Here https://github.com/chaimPaneth/react-native-jw-media-player/pull/50

If you have time and have your own Advertisement Data Manifest File, please test using that PR's branch.


Thanks :D

**Comment by chaimPaneth** [comment]
Hi all.

I've merged PR https://github.com/chaimPaneth/react-native-jw-media-player/pull/50 for ad support.

Thank you @ybbond.
