### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNJWPlayerView" was not found in the UIManager.

### ISSUE THREAD

**Issue by artfullsoul-dj** [chaimPaneth/react-native-jw-media-player#183]
I integrated the player in the same way as in doumentation but this issue is comming while running the app.

Invariant Violation: requireNativeComponent: "RNJWPlayerView" was not found in the UIManager.

This error is located at:
    in RNJWPlayerView (created by JWPlayer)
    in JWPlayer (created by App)
    in RCTView (created by View)
    in View (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules\react-native\Libraries\LogBox\LogBox.js:149:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:60:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:34:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:172:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:123:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:177:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:437:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:388:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:132:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:365:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:131:4 in flushedQueu

**Comment by kundarmah** [comment]
Kindly rebuild the app after installing the library

**Comment by chaimPaneth** [comment]
Hi @lopongoaca 

Did you did you follow the installation instructions ->
- npm install react-native-jw-media-player --save
- cd ios && pod install
- reopen your .xcworkspace (white icon no the blue .xcodeproj)
- rerun project

If yes can you please share your code where you render the player, and check out the example app for reference.

Keep me updated please,
Thank you,
Chaim

**Comment by owais-star** [comment]
[iOS] RNJWPlayer is not getting installed on pod install #233 
@chaimPaneth i belive this issue is not reproducable in the react-native-version of the example app, i have tested in the versions (react-native 0.68.2 & 0.69.3) they are above the react-native version of the example app and in these versions when we do pod-install the RNJPlayer and GoogleCast packages are not installed in Pods thats'why no matter how many times we rebuild the app we will get the same error

**Comment by marc-slashmobility** [comment]
Same happening on RN 0.69.4, is there any kind of fix for this??

**Comment by danimarin** [comment]
I have this issue when upgrading from 0.68.x to 0.69.x

**Comment by mukeshInf** [comment]
[Info] 10-28 21:10:00.630 20471 29463 E ReactNativeJS: Invariant Violation: requireNativeComponent: "RNJWPlayerView" was not found in the UIManager.
10-28 21:10:00.630 20471 29463 E ReactNativeJS: 
10-28 21:10:00.630 20471 29463 E ReactNativeJS: This error is located at:
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNJWPlayerView (at react-native-jw-media-player/index.js:448)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in JWPlayer (at JWAVPlayer/index.js:42)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StyledNativeComponent (created by Styled(View))
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Styled(View) (at JWAVPlayer/index.js:41)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StyledNativeComponent (created by Styled(View))
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Styled(View) (at JWAVPlayer/index.js:40)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at SafeAreaView.js:41)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SafeAreaView
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StyledNativeComponent (created by Styled(Component))
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Styled(Component) (at JWAVPlayer/index.js:39)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in JWAVPlayer (at SceneView.tsx:132)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StaticContainer
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:124)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:217)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at DebugContainer.native.tsx:27)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in DebugContainer (at NativeStackView.native.tsx:76)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeNestedStack (at NativeStackView.native.tsx:288)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreen (at createAnimatedComponent.js:242)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponent (at createAnimatedComponent.js:295)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponentWrapper (at src/index.native.tsx:257)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeFreeze (at src/index.native.tsx:256)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Screen (at NativeStackView.native.tsx:214)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SceneView (at NativeStackView.native.tsx:342)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreenStack (at src/index.native.tsx:188)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in ScreenStack (at NativeStackView.native.tsx:331)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in NativeStackViewInner (at NativeStackView.native.tsx:388)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at SafeAreaProviderCompat.tsx:42)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SafeAreaProviderCompat (at NativeStackView.native.tsx:387)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in NativeStackView (at createNativeStackNavigator.tsx:72)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Unknown (at createNativeStackNavigator.tsx:71)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in NativeStackNavigator (at AppNavigator.js:118)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in PodcastsStackScreen (at SceneView.tsx:132)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StaticContainer
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:124)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:217)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at Screen.tsx:63)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at Background.tsx:13)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Background (at Screen.tsx:58)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Screen (at BottomTabView.tsx:130)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreen (at createAnimatedComponent.js:242)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponent (at createAnimatedComponent.js:295)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponentWrapper (at src/index.native.tsx:257)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeFreeze (at src/index.native.tsx:256)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Screen (at ScreenFallback.tsx:38)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeScreen (at BottomTabView.tsx:123)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreenContainer (at src/index.native.tsx:330)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in ScreenContainer (at ScreenFallback.tsx:29)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeScreenContainer (at BottomTabView.tsx:93)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at SafeAreaProviderCompat.tsx:42)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SafeAreaProviderCompat (at BottomTabView.tsx:92)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in BottomTabView (at createBottomTabNavigator.tsx:118)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Unknown (at createBottomTabNavigator.tsx:117)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in BottomTabNavigator (at AppNavigator.js:165)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in TabScreen (at SceneView.tsx:132)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in StaticContainer
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:124)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:217)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at DebugContainer.native.tsx:27)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in DebugContainer (at NativeStackView.native.tsx:76)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeNestedStack (at NativeStackView.native.tsx:288)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreen (at createAnimatedComponent.js:242)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponent (at createAnimatedComponent.js:295)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in AnimatedComponentWrapper (at src/index.native.tsx:257)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in MaybeFreeze (at src/index.native.tsx:256)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in Screen (at NativeStackView.native.tsx:214)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SceneView (at NativeStackView.native.tsx:342)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RNSScreenStack (at src/index.native.tsx:188)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in ScreenStack (at NativeStackView.native.tsx:331)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in NativeStackViewInner (at NativeStackView.native.tsx:388)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in RCTView (at View.js:32)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in View (at SafeAreaProviderCompat.tsx:42)


[Info] 10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in SafeAreaProviderCompat (at NativeStackView.native.tsx:387)
10-28 21:10:00.630 20471 29463 E ReactNativeJS:     in NativeStackView (at createNativeStackNavigator.tsx:72


Facing this issue in Android only.

**Comment by ddolheguy** [comment]
This can be closed as fixed in the latest `0.2.27` update

**Comment by mahmudsg** [comment]
Hi @ddolheguy, @chaimPaneth,
We are getting the same error! Could you please help? 

we are using the **react-native-tvos** package with the typescript template. 
The JW player works well on iPhone simulators but when trying to run the same code on a **Apple TV** simulator, getting the following error, 

_requireNativeComponent: "RNJWPlayerView" was not found in the UIManager._

we have tried 0.2.35 and 0.2.27 versions.
