### ISSUE TITLE
Build input file cannot be found.

### ISSUE THREAD

**Issue by bsmith-ine** [chaimPaneth/react-native-jw-media-player#19]
Build input file cannot be found: '../node_modules/react-native-jw-media-player/ios/CustomJWPlaylistItem.m'

This file is not currently in this repo, however, when I checkout the forks on this repo, it is present. Why was this file removed?

**Comment by chaimPaneth** [comment]
@bsmith-ine 

This file is no longer used so it was deleted, if you erase the library from node_modules and npm i again you won't have this error as it will not be installed or referenced.
