### ISSUE TITLE
cannot find protocol declaration for 'JWPlayerViewDelegate';

### ISSUE THREAD

**Issue by chrisdugne** [chaimPaneth/react-native-jw-media-player#194]
Hello,

- I updated to RN 67
- Using XCode 13.0
- I'm using `v0.2.10`, I tested and got the same issue with `v0.2.12`

now building with 

```sh
xcodebuild build -workspace MY.xcworkspace -scheme myscheme -sdk iphonesimulator
```

I hit many `cannot find protocol declaration` errors like:

```sh
/ios/build/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/JWPlayerKit/JWPlayerKit.framework/Headers/JWPlayerObjCViewController.h:20:1: error:
      cannot find protocol declaration for 'JWPlayerViewDelegate';
```

## notes:

- building for `-sdk iphoneos` is working properly
- tested with `RN 64`, and `RN 66`: building with `-sdk iphonesimulator` is working properly (`v0.2.10`)
- I've no such errors with other libs, so it might well be an issue here

thanks for any fix/guidance

**Comment by chaimPaneth** [comment]
Hi @chrisdugne 

I had this issue seems that clearing cache doesn't work, what I did was update my project to RN version 68 and it compiled.

**Comment by chrisdugne** [comment]
ok thanks for the input @chaimPaneth , I'll try and let you know.

**Comment by chrisdugne** [comment]
Hello, still the same issue with RN68 on my side :(

**Comment by chaimPaneth** [comment]
Hi @chrisdugne 

Did you see those issues [32432](https://github.com/facebook/react-native/issues/32432) & [834#issuecomment-605448785](https://github.com/facebook/flipper/issues/834#issuecomment-605448785)

Seems like the one we got,
Lemme know.

**Comment by chrisdugne** [comment]
Hi @chaimPaneth 
the issue you pointed seems not the same as this one here;

I finally got my build working by specifying the arch:

working example: 
```sh
 xcodebuild ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO clean build -workspace MY.xcworkspace -scheme MYscheme -sdk iphonesimulator -configuration Release -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'
```

**Comment by chaimPaneth** [comment]
Wow Thanks @chrisdugne

I just got this issue before and this fixed it for me!

I'm adding a screenshot on how to change those values in xcode itself ->

<img width="750" alt="Screen Shot 2022-05-04 at 9 55 26 PM" src="https://user-images.githubusercontent.com/20083971/166809520-12508c61-ec01-4d90-af57-d666ab9ce54f.png">

Thanks.
