### ISSUE TITLE
[ios] controls not visible

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#198]
I'm upgrading from 0.1.57 to 0.2.14
Everything works fine on Android. But on iOS it does not show any controls.
`player.setControls(true);` also does not work.

Also image is not visible for audio content while on Android it works as expected.

my config: 

```
{
      license:
        Platform.select({
          ios: JW_PLAYER_LICENSE_IOS,
          android: JW_PLAYER_LICENSE_ANDROID,
        }) ?? '',
      controls: true,
      viewOnly: false,
      repeat: false,
      playlist: [_playlistItem],
      interfaceBehavior: 'normal',
      autostart: true,
      backgroundAudioEnabled: true,
}
```

Also the component has config prop as true

```
...
 <JWPlayer
        ref={playerRef}
        style={styles.flex}
        config={config}
        controls={true}
...
```

EDIT:
player.setControls(true) does not work on iOS because [this if statement](https://github.com/chaimPaneth/react-native-jw-media-player/blob/689172ef7a9c6dead4c68a856ac83f1d8f3ec6aa/ios/RNJWPlayer/RNJWPlayerViewManager.m#L474
) is always false

**Comment by KestasVenslauskas** [comment]
No update on this? Does others manage to get controls on the iOS?

**Comment by chaimPaneth** [comment]
@KestasVenslauskas can you provide a screenshot of the player and some code of the player configuration.

Thanks.

**Comment by KestasVenslauskas** [comment]
This is my player implementation for v0.2.x:
https://github.com/lrtlt/mobile/blob/jw-player-update/app/components/videoComponent/JWPlayerNative.tsx
This is an open source project I'm maintaining you can freely clone repo.
Update is on `jw-player-update` branch, if you are on M1 chip then use `m1-compat-light` branch.

**Comment by KestasVenslauskas** [comment]
Here is the iOS player for video (no controls):
![Simulator Screen Shot - iPhone 13 - 2022-05-25 at 11 12 02](https://user-images.githubusercontent.com/52245569/170218084-44b2119d-63f0-4163-b4b8-da4d940ea3ff.png)
Here is the Android player for video (with controls):
![Screenshot_20220525_113002](https://user-images.githubusercontent.com/52245569/170218211-d57a216e-bb54-4a66-9c70-1536a6930f52.png)
Here is the iOS player with audio & backgroundImage set (background image not visible & controls not shown):|
![Simulator Screen Shot - iPhone 13 - 2022-05-25 at 11 20 23](https://user-images.githubusercontent.com/52245569/170218328-61ccc5b2-8fda-4269-9eb4-0ab20435c232.png)
Here is the Android player with audio & background image (everything works as expected):
![Screenshot_20220525_112858](https://user-images.githubusercontent.com/52245569/170218467-c21c26c8-270b-4719-83c1-2007ff47b001.png)

**Comment by chaimPaneth** [comment]
@KestasVenslauskas I think your issue is that your passing `viewOnly: false` while in the code i don't check `viewOnly == true` only if `viewOnly != nil`; my mistake I will fix it, but try to just not pass `viewOnly` at all it should render the playerViewController I think / hope

Lemme know

**Comment by KestasVenslauskas** [comment]
If I remove "viewOnly" param I get this error (audio playing in the background):
![Simulator Screen Shot - iPhone 13 - 2022-05-25 at 14 43 29](https://user-images.githubusercontent.com/52245569/170254404-55a3dbd0-2398-4ece-8f28-03a097c666e7.png)

**Comment by chaimPaneth** [comment]
I will check out the last crash but there is another issue about this here https://github.com/chaimPaneth/react-native-jw-media-player/issues/174 I'll reopen the discussion there about this
