### ISSUE TITLE
Build errors with M1

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#205]
Was trying to update my project to be compatible with M1 chip.
Passed many errors with different libraries but now I'm just stuck with this one.

There is a lot of errors building this project as a dependency with M1:
<img width="1252" alt="Screenshot at May 20 16-30-01" src="https://user-images.githubusercontent.com/52245569/169540245-fb223b5a-9666-4195-8444-bed507b2391e.png">

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

Seems like it's related to this issue https://github.com/chaimPaneth/react-native-jw-media-player/issues/194

Can you confirm?

Thanks

**Comment by KestasVenslauskas** [comment]
@chaimPaneth If I follow those steps other libraries starts to break... :/

**Comment by chaimPaneth** [comment]
@KestasVenslauskas If you remove this library do you get a successful build?

**Comment by chaimPaneth** [comment]
@KestasVenslauskas We'll discuss further in this issue about ios controls https://github.com/chaimPaneth/react-native-jw-media-player/issues/198

Thanks.
