### ISSUE TITLE
Android back button does not minimize player

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#207]
If you are looking at fullscreen video on android and press back button player goes black (but still shown fullscreen black screen). That's because navigation goes down the backstack and player view is not present any more. You can also press back again to shut down the app, but the fullscreen video remains untill it's shutdown.

**Comment by KestasVenslauskas** [comment]
For others if this may help there is quick workaround:
```
 useEffect(() => {
    const backHandlerSubscription = BackHandler.addEventListener('hardwareBackPress', () => {
      playerRef.current?.setFullscreen(false);
      return false;
    });

    return () => {
            backHandlerSubscription.remove();
    };
  }, []);
```

**Comment by KestasVenslauskas** [comment]
Made a PR for this fix: https://github.com/chaimPaneth/react-native-jw-media-player/pull/209

**Comment by chaimPaneth** [comment]
Merged
