### ISSUE TITLE
upgrade exo player to 2.17.1 

### ISSUE THREAD

**Issue by nateshmbhat** [chaimPaneth/react-native-jw-media-player#213]
From 2.16 to 2.17 , many api changes have happened in exo-player. Please add support for exo player 2.17 so that other RN libraries which are using 2.17 version of exo-player, can also work with this.

**Comment by arvkmr** [comment]
I see exo-player version was updated to 2.18.1 on 0.2.29 release but then in the next release it was degraded down to 2.16.1 again, I'm intrested to know the reason for going back and a possible date on when we can expect to go back up to 2.18.1 again?

**Comment by chaimPaneth** [comment]
Hi @arvkmr We had to downgrade the library in certain versions due to JW sdk having some issue with our implementation but as of now the latest implements exo version 2.18.1
