### ISSUE TITLE
Can we use this library just to play mp3 audio and not a video?

### ISSUE THREAD

**Issue by nateshmbhat** [chaimPaneth/react-native-jw-media-player#214]
can we use this library as an audio player for certain use cases?

**Comment by chaimPaneth** [comment]
Hi @nateshmbhat sure, you can even just not give any width / height to the player and it will just play the track while hidden (no width and height).

Lemme know if you managed.

**Comment by nateshmbhat** [comment]
For local files , i needed prefix with the "file:///" protocol in ios for it to play without issues.
