### ISSUE TITLE
loadPlaylist function is undefined in the jwplayer reference

### ISSUE THREAD

**Issue by nateshmbhat** [chaimPaneth/react-native-jw-media-player#218]
As per docs and the type defs, loadPlaylist is supposed to load a new playlist array, this function is undefined in the current version of jw media player (2.2.0)

**Comment by chaimPaneth** [comment]
Hi @nateshmbhat I removed it from the docs, it was leftover from previous versions.

Thanks.

**Comment by nateshmbhat** [comment]
@claimPaneth is there a way to load a Playlist imperatively?

I tried rerendering with new value of Playlist but it didn't work unless
the whole component was remounted with the new value of Playlist.
