### ISSUE TITLE
[IOS]background audio controls last video on page instead of video being played

### ISSUE THREAD

**Issue by msuresh1993** [chaimPaneth/react-native-jw-media-player#24]
We are using background audio on a page which has multiple videos. 
When we play a video, we are able to see the background audio control in the notification center(NC) but when we click pause from the NC, it controls the last video on the page(not the video being played).

**Comment by chaimPaneth** [comment]
@msuresh1993 

Is this issue still happening in the latest version?

**Comment by BeshoySarkis** [comment]
Yes, anytime you have more than 1 instance initiated the background controls are referencing the last instantiated instance rather than the one being palyed

**Comment by BeshoySarkis** [comment]
This should have been fixed by JW in iOS release 3.14

"Fixed conflicts encountered when interacting with and resuming playback from the lock screen when there are multiple active players on the same screen."

https://www.jwplayer.com/release-notes/ios-sdk/?id=26241426

**Comment by chaimPaneth** [comment]
@BeshoySarkis can you confirm that it's working in the latest version of this library 0.1.48

Thanks
