### ISSUE TITLE
Picture in picture not working

### ISSUE THREAD

**Issue by safwanchundakkadan** [chaimPaneth/react-native-jw-media-player#241]
The "picture in picture" is not working in ios

code--
<Player
              ref={playerRef}
              style={{flex: 1}}
              config={{
                pipEnabled: true,
                autostart: true,
                playlist: [
                  {
                    startTime: starttime,
                    file: itemurl,
                    image: image,
                  },
                ],
                styling: {
                  colors: {},
                },
                related: {
                  url: playlistid,
                },
              }}
              onTime={onTime}
              onFullScreen={onFullScreen}
              onFullScreenExit={onFullScreenExit}
            />

**Comment by chaimPaneth** [comment]
Check out this issue I've added more information https://github.com/chaimPaneth/react-native-jw-media-player/issues/258#issuecomment-1374935827
