### ISSUE TITLE
[Doubt] [Improvement] Handle Error

### ISSUE THREAD

**Issue by jacksonsmith** [chaimPaneth/react-native-jw-media-player#245]
Platform: iOS
JwPlayerKit Version: 4.6.2
react-native-jw-media-player version: 2.2.7

Hello Everyone,

Was that way to handle error updated ?

on doc, we have this examle `onPlayerError={event => this.onPlayerError(event)}`

but I only could handle with that:

`onPlayerError={event => this.onPlayerError(event.nativeEvent.error)}`
<img width="528" alt="image" src="https://user-images.githubusercontent.com/16623863/201360652-9b35b76c-7805-4151-8fe8-25b4645e23e4.png">

if needed, we can make a PR, to back Contract work again.

See ya.

**Comment by chaimPaneth** [comment]
Hi @jacksonsmith you're handling it correct in the latest version I've also updated the types.
