### ISSUE TITLE
Chromecasting Issue with dynamic playlist

### ISSUE THREAD

**Issue by SufianBabri** [chaimPaneth/react-native-jw-media-player#254]
My app has a flow similar to YouTube (with autoplay set to ON) where the user opens a video and the app will keep on playing the next video (we don't know all the next videos in advance).

Once the current video's playback is over, I change the playlist in the state, which causes a re-render of the JWPlayer component.

```
const Player = React.useMemo(
	() => (
		<JWPlayer
			ref={jwPlayer}
			key={tag}
			style={styles.player}
			config={{
				license: Platform.OS === 'ios' ? IOS_JWP_API_KEY : ANDROID_JWP_API_KEY,
				playlist: [
					{
						mediaId: video.mediaId,
						image: video.thumbnails.thumbnail,
						file: video.url,
						autostart: true
					}
				]
			}}
			onPlaylistComplete={onPlaylistComplete}
			onComplete={onComplete}
		/>
	),
	[video]
);
```

This works fine till I start casting to Chromecast (which shows a blue Chromecast icon once the first video completes).

My understanding is that it happens because I am re-initializing the JWPlayer, which breaks its connection to Chromecast.

To resolve this issue I think a function (in the JWPlayer object) to change playlist is needed.

Can anyone give me pointers about what files I will likely be adding code to, given I am still new to Native Modules and am experienced with native Android development?

**Comment by rymate1234** [comment]
We're having a similar issue with this on iOS, except the app crashes when the component re-renders

**Comment by SufianBabri** [comment]
@rymate1234 I have added the feature for Android in a branch named **feature/change-playlist** in [a fork of this library](https://github.com/sufianbabri/react-native-jw-media-player/tree/feature/change-playlist).

I think you'll need to do similar for iOS. If you are able to, please create a PR to this (ChaimPaneth's library). This has to be the most important feature for some apps.

Feel free to use my code. :)

If I get more time, I hope to add this feature to iOS but it seems I will be unable to do so before 3 to 4 weeks, at a minimum.

To install this modified package, I simply run:
```console
yarn add git+https://github.com/SufianBabri/react-native-jw-media-player#feature/change-playlist
```

And then I can invoke the function like this:
```ts
jwPlayer.current?.loadPlaylist([
    {
        title: "video1",
        mediaId: "1",
        file: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        autostart: true
    },
    {
        title: "video2",
        mediaId: "2",
        file: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        autostart: true
    }
]);
```

**Comment by chaimPaneth** [comment]
We used to have a setPlaylist / loadPlaylist function I will add in the next version.

**Comment by SufianBabri** [comment]
Closing this issue as the feature has been added in version 0.2.34
