### ISSUE TITLE
Cannot build in ios

### ISSUE THREAD

**Issue by bittu1028** [chaimPaneth/react-native-jw-media-player#28]
Build input file cannot be found: '../node_modules/react-native-jw-media-player/ios/CustomJWPlaylistItem.m'

**Comment by cmcaboy** [comment]
It looks like the older version of the library used these files. I'm guessing we will need to put these files back in or cleanup the build process to not be dependent on said files.

![image](https://user-images.githubusercontent.com/1489169/73753883-631c7380-4731-11ea-865c-90109e8bd5a9.png)

CustomJWPlayerListItem.h
```
#import <JWPlayer_iOS_SDK/JWPlayerController.h>

NS_ASSUME_NONNULL_BEGIN

@interface CustomJWPlaylistItem : JWPlaylistItem

@property (readwrite) NSInteger seekTime;

@end

NS_ASSUME_NONNULL_END
```

CustomJWPlaylistItem.m
```
#import "CustomJWPlaylistItem.h"

@implementation CustomJWPlaylistItem

@end
```

**Comment by chaimPaneth** [comment]
@bittu1028 

What version of the library did you install? as @cmcaboy has replied above those files were removed in the later versions.

Try deleting the library from node_modules and reinstalling the latest version.

**Comment by cmcaboy** [comment]
@chaimPaneth This is still very much an issue. I tried the following and still ran into the build error.

1. unlinked the old version
2. upgraded the library
3. blew away node_modules
4. ran yarn install
5. blew away and recreated pods
6. refreshed the cache
7. blew away the ios build directory

After doing all of these, I still receive the error.

![image](https://user-images.githubusercontent.com/1489169/74298953-38c24b80-4d19-11ea-86e7-95e1d23a0d17.png)

**Comment by cmcaboy** [comment]
You need to remove "CustomJWPlayListItem.m" from Compile Sources. It will then compile. I'll prepare a PR.

![image](https://user-images.githubusercontent.com/1489169/74299896-10881c00-4d1c-11ea-8ad4-0a57a7dd1d2d.png)

**Comment by cmcaboy** [comment]
I submitted #35 to fix this.
