### ISSUE TITLE
onFullScreen and onFullScreenExit work fine on Android but do not work on iOS

### ISSUE THREAD

**Issue by grigdodon** [chaimPaneth/react-native-jw-media-player#283]
onFullScreen and onFullScreenExit work fine on Android but do not work on iOS. anyone can help please?
thank you!

```
<JWPlayer
      onLayout={onLayout}
      ref={ref}
      key={tag}
      style={[{ flex: 1 }, style]}
      config={{
        license: Platform.select({ ios: IOS_API_KEY, android: ANDROID_API_KEY }),
        backgroundAudioEnabled: true,
        portraitOnExitFullScreen: true,
        landscapeOnFullScreen: true,
        fullScreenOnLandscape: true,
        ...props.config,
      }}
      {...newProps}
      onPlayerError={(e) => {
        console.log(e.nativeEvent);
        alert(e.nativeEvent?.error || 'Player Error.');
      }}
      onFullScreen={(e) => {
        console.log(e, 'on full screen');
      }}
      onFullScreenExit={(e) => {
        console.log(e, 'on full screen exit');
      }}
/>
```

```
"react": "18.2.0"
"react-native": "0.71.3"
"react-native-jw-media-player": "^0.2.35"

**Comment by maltenz** [comment]
I am having the same issue after upgrading from 0.2.34 to 0.2.35

**Comment by nateshmbhat** [comment]
same issue

**Comment by nateshmbhat** [comment]
@chaimPaneth could be related to the delegate setting methods that were removed recently in the 2.3.5 release

**Comment by chaimPaneth** [comment]
Hi @nateshmbhat 

It can very possibly be the removal of the delegates, but I was told by JW that the JWObjCViewController doesn't need to set those delegates as it implements those already on itself. You can see when setting the delegates manually you get a warning because it already set the delegates... I will contact them about the onFullscreen callbacks.

**Comment by IntelliJAbhishek** [comment]
@chaimPaneth this issue is not been fixed . I tried building from master branch. Its not related to removing those delegate methods.

**Comment by grigdodon** [comment]
@chaimPaneth `onFullScreenExit` not being triggered since 0.2.35. I am stuck on 0.2.34. Any advice please?
