### ISSUE TITLE
allow setting multiple values for hideUiGroup

### ISSUE THREAD

**Issue by nateshmbhat** [chaimPaneth/react-native-jw-media-player#284]
I want to hide both `casting_menu` and `playback_submenu` in android. but right now hideUiGroup only takes single value. please add support to hide multiple items.

purhaps you can merge this feature with setVisibility method to work for both ios and android

**Comment by razorRun** [comment]
@nateshmbhat thanks for the Fix, however I tried this and doesn't seems to work for me. Can you maybe share a sample code for this ? 

@chaimPaneth can we kindly get this into your list.. also maybe a release with this and iOS visibility..

**Comment by nateshmbhat** [comment]
@razorRun heres the sample code

```
<JWPlayer
        config={{
          ...
          hideUIGroups: ['casting_menu', 'settings_menu']
}}
```

**Comment by chaimPaneth** [comment]
Merged

**Comment by razorRun** [comment]
💪
