### ISSUE TITLE
adSchedule Error ios vast ads  

### ISSUE THREAD

**Issue by blinkz333** [chaimPaneth/react-native-jw-media-player#287]
I tried to set up my advertising like this 

```
advertising: {
      adClient: "vast",
      adSchedule: [
        {
          tag: "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480|770x433&iu=/231599934,9206757/thairath/tv-live/video/&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=https://www.thairath.co.th/tv/live&description_url=https://www.thairath.co.th/tv/live&correlator=__timestamp__&vpos=preroll&ad_rule=0",
          offset: "pre"
        }
      ],
    },
```

It's show Error like this 

![Screenshot 2566-03-15 at 18 02 14](https://user-images.githubusercontent.com/35993754/225290338-7b2f785e-735d-4abd-8f7b-8d13e2d99547.png)

Android is can run normally , Sorry for wrong grammar

**Comment by chaimPaneth** [comment]
Hi @blinkz333

There is an issue with how the url is parsed here because of it containing another url substring, try encoding it first, I will also add to next version a native encoding to parse the url.

Thanks.
