### ISSUE TITLE
Crash on android 9-10

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#29]
From crashlytics. Latest version 2020-02-02

```
Fatal Exception: java.lang.IllegalArgumentException
Service not registered: com.appgoalz.rnjwplayer.RNJWPlayerView$1@7843d02
android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1344)

android.content.ContextWrapper.unbindService (ContextWrapper.java:655)
CRASH >>> com.appgoalz.rnjwplayer.RNJWPlayerView.doUnbindService (RNJWPlayerView.java:625)
```

**Comment by chaimPaneth** [comment]
@KestasVenslauskas 

Hi, seems as though the service wasn't registered, did you follow the instructions in the readme specifically adding this to AndroidManifest.xml?

```
<receiver android:name="androidx.media.session.MediaButtonReceiver">
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
<service
    android:name="com.appgoalz.rnjwplayer.MediaPlaybackService"
    android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</service>
```

**Comment by KestasVenslauskas** [comment]
I did, service works fine, I can reproduce it 4 out of 10 times on my
android 10 device. But its happening on many Android versions. I start the
player then notification shows up and I minimize the app. Boom crash, but
sometimes if works.

**Comment by KestasVenslauskas** [comment]
@chaimPaneth some statistics:
Daily active users 5.7K
Crashes 321
Users affected 231

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

The issue your having might be related this:
https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

It's a known issue with foreground service,
Is this the crash you're getting?

**Comment by KestasVenslauskas** [comment]
@chaimPaneth No it's not this. It's clearly NPE if you go to the line the error happens in. Because it tries to do something with the View which is null. Still happening on latest version.

**Comment by KestasVenslauskas** [comment]
@chaimPaneth Added PR with a fix for this issue hope it helps.
The issue is that RNJWPlayerView tries to unbind Service by using Activity instance. But when app is in background for a longer time it's activity get destroyed by Android OS. That's why we need to use Application Context because Service outlives the Activity but not the application.
