### ISSUE TITLE
Getting blank Screen while playing video but audio is working 

### ISSUE THREAD

**Issue by panchalsanket** [chaimPaneth/react-native-jw-media-player#3]

**Comment by chaimPaneth** [comment]
Hi @panchalsanket 

How are you loading the player?
 
If you're using the loadPlaylistitem method you might need to call it with a timeout as it takes a few milliseconds that the player finishes mounting.

Try using the playlistItem prop or putting loadPlaylistitem call in a setTimeout.

See the updated readme.

Also make sure your player styles are correct so it has height to show the video screen.

Thanks

**Comment by codal-mpawar** [comment]
@panchalsanket @chaimPaneth   I have also the same issue first play audio and then after play video in a few seconds.

**Comment by codal-mpawar** [comment]
@panchalsanket I solve this issue send me your setup in android as well as ios.

**Comment by codal-mpawar** [comment]
@panchalsanket 
I follow this document https://github.com/chaimPaneth/react-native-jw-media-player
in android  
other things follow the same as write steps.
android/build.gradle paste this item only
maven {
            url 'http://mvn.jwplayer.com/content/repositories/releases/'
        }
android/app/build.gradle
in ios is not a problem same as setup
