### ISSUE TITLE
Custom style must be remote, cannot use local css file

### ISSUE THREAD

**Issue by ybbond** [chaimPaneth/react-native-jw-media-player#30]
## Detail

I tried adding css file on the android `assets` folder, but it has no effect. I see the implementation is looking up to the `String.format(file:///android_asset/%s.css, name)`. To no effect.

## Further Research

I did some research and it said that JWPlayer has no support for local css file,

[1] https://jwplayer-support-archive.netlify.com/questions/17033726-player-config-cssskin-local-file

[2] https://github.com/jwplayer/jwplayer/issues/2722

**Comment by chaimPaneth** [comment]
Hi @ybbond 

We are using local css files in many projects and it is working fine, are you sure you have followed the instructions correctly as follows:

1. Drag css file in to app/src/main/assets folder.
2. The theme name should match the file name e.g for a file named video.css your css class definition should be as so
```
/* Use this class to set a global background color for all elemnts. */
.jwplayer.jw-skin-video .jw-background-color {
  background: #000;
}

/* Control bar */
.jwplayer.jw-skin-video .jw-controls .jw-controlbar {
  background: transparent;
}

/* Duration text */
.jwplayer.jw-skin-video .jw-controls .jw-controlbar .jw-button-container .jw-text {
  color: #E1E2E1;
}

/* Slider time container */
.jwplayer.jw-skin-video .jw-controls .jw-controlbar .jw-slider-time {
  /*position: absolute;*/
  /*bottom: 15px;*/
  background: transparent;
  box-shadow: none;
}
```
Basically follow the following structure .jwplayer.jw-skin-{filename}

3. Finally pass the file name e.g. "video" into jw params playerStyle={name}

Also try to put the param on the player itself and into the playListItem object as so:
```
playerStyle={"video"}
   playlistItem={{
   playerStyle: "video",
   title,
   file,
    mediaId,
    image,
    desc,
    autostart,
    controls,
    repeat,
    displayDescription,
    displayTitle
}}
```

Can you confirm this is working for you?
Thanks

**Comment by chaimPaneth** [comment]
I'm closing  due to inactivity.

**Comment by QuentinJ-LV** [comment]
Hi @chaimPaneth, I think it could be usefull to create an example where you use a simple playerStyle modifying the player.

Also about your upcoming solution, you can't pass :

`playListItem={{
    playerStyle: "video"
}}`

Since playerStyle is not a prop that can be passed in playListItem (at least at that time) from your type :

`interface PlaylistItem {
    mediaId?: number;
    startTime?: number;
    adVmap?: string;
    adClient?: string;
    adSchedule?: { tag: string; offset: string };
    desc?: string;
    file?: string;
    image?: string;
    title?: string;
    autostart?: boolean;
    controls?: boolean;
    displayDescription?: boolean;
    displayTitle?: boolean;
    repeat?: boolean;
    backgroundAudioEnabled: boolean;
  }`
