### ISSUE TITLE
Android: Latest 0.2.36 version fails to build due to react-native-jw-media-player reference

### ISSUE THREAD

**Issue by ddolheguy** [chaimPaneth/react-native-jw-media-player#305]
Using the latest released version of this library 0.2.36, it failed to build on Android due to the below error.

NOTE: This happens also with the packaged Example project in this repo.

* What went wrong:
A problem occurred evaluating project ':react-native-jw-media-player'.
> Project with path ':react-native-android-media-browser' could not be found in project ':react-native-jw-media-player'.

**Comment by chaimPaneth** [comment]
Hi @ddolheguy,

Fixed in 0.2.37.

Thanks
