### ISSUE TITLE
Fullscreen Events not working in latest build 

### ISSUE THREAD

**Issue by ddolheguy** [chaimPaneth/react-native-jw-media-player#309]
Using the latest build, events such as `onFullScreen`, `onFullScreenExit` and `onFullScreenRequested` are not firing on iOS.

I've debugged this and in the `RNJWPlayerViewController.m` file, the `JWFullScreenViewController` events seem not the be firing as expected.  For example, setting a debugger on the below fails to fire when going full screen.

`
- (JWFullScreenViewController * _Nullable)playerViewControllerWillGoFullScreen:(JWPlayerViewController * _Nonnull)controller {
    if (_parentView.onFullScreenRequested) {
        _parentView.onFullScreenRequested(@{});
    }
    return nil;
}
`

**Comment by grigdodon** [comment]
hey. were they working for you in the previous versions?
I am stuck on 0.2.34 because the onFullScreenExit event is not being fired.

**Comment by grigdodon** [comment]
hey @chaimPaneth sorry to bother you. any chance you can give an update on this? Maybe the fullscreen events work now in a different way than the documentation says? any help will be highly appreciated! thank you!

I can't manage to have the full screen events work from version 0.2.34 onwards. Thank you!

**Comment by chaimPaneth** [comment]
Hey guys is this working for you on the latest version.

**Comment by grigdodon** [comment]
> Hey guys is this working for you on the latest version.

yes. thank you for sorting this out!

not related to this issue, but it looks like casting on android still not works. any chance to have the option to not add google cast by default in the library so we can control the casting or maybe the issue can be fixed?

**Comment by chaimPaneth** [comment]
Thanks @grigdodon I'm closing this and will check and update about casting here https://github.com/chaimPaneth/react-native-jw-media-player/issues/314
