### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#31]
Is there plans for Chromecast support on android?

**Comment by ludovit-ubrezi** [comment]
+ same question :)

**Comment by chaimPaneth** [comment]
I'm adding jwplayer [casting](https://support.jwplayer.com/articles/how-to-enable-casting-and-airplay#:~:text=To%20enable%20casting%20for%20a,SDK%20or%20iOS%20SDK%20directly.&text=From%20your%20list%20of%20players,click%20the%20toggle%20to%20ON) in the next version, it will be ready in the next few days.
