### ISSUE TITLE
Support for Android 13?

### ISSUE THREAD

**Issue by spencervbishop-dr** [chaimPaneth/react-native-jw-media-player#320]
Hi, the library seems to work well for iOS but the Android app is not initializing the player. 
I see that the build.gradle file has the compile version set to API 28. Do you know if this library is compatible with Android 13 (API level 33)? 
Is anyone else using this library for Android 13 successfully?

RN version = 0.72
New Architecture = true
react-native-jw-media-player version = 0.2.39

**Comment by chaimPaneth** [comment]
Hi @spencervbishop-dr 

I'm using the library successfully targeting the latest API's whatever you set in the app/build.gradle will be used.
