### ISSUE TITLE
How to play only a single video at a time in flatlist 

### ISSUE THREAD

**Issue by Kadir-prog** [chaimPaneth/react-native-jw-media-player#326]
hi @chaimPaneth we are using this library to show videos like reels but we found some issues like player are playing all videos at same time with audio can you please help me to show single video at a time 

https://github.com/chaimPaneth/react-native-jw-media-player/assets/80304501/2c454698-22c9-41ab-b75a-e4cff9a68cfe

**Comment by chaimPaneth** [comment]
Hi @Kadir-prog 

Check out the example app we have there an example with a list of players.

Lemme know.

**Comment by Kadir-prog** [comment]
hi @chaimPaneth can please share me example link so i can check please help which example is supported for this one

**Comment by chaimPaneth** [comment]
Hi @Kadir-prog 

Check this out https://github.com/chaimPaneth/react-native-jw-media-player/blob/master/Example/app/jsx/screens/ListExample.js.

Thanks.
