### ISSUE TITLE
error: Build input file cannot be found

### ISSUE THREAD

**Issue by faisalansari97** [chaimPaneth/react-native-jw-media-player#33]
Hii, I am not able to run my project in xcode. 

error: Build input file cannot be found: '/Users/user/WorkSpace/git/slp/node_modules/react-native-jw-media-player/ios/CustomJWPlaylistItem.m' (in target 'RNJWPlayer' from project 'RNJWPlayer')

Seems like CustomJWPlaylistItem.m file is missing. I have tried to run pod install. Link and relink the library multiple times but it didn't work. 

Project dependencies:
"react-native-jw-media-player": "0.1.32",
"react": "^16.8.3",
"react-native": "^0.59.10"

**Comment by cmcaboy** [comment]
I submitted #35 to fix this.

**Comment by chaimPaneth** [comment]
Merged in version 0.1.34
