### ISSUE TITLE
Add onAdImpression

### ISSUE THREAD

**Issue by DevineDecrypter** [chaimPaneth/react-native-jw-media-player#331]
Hey, in the JW Player documentation, for Advertisements there are lots of events.
Right now we have custom controls, and we would like to know when the AD starts to load and play.
In the documentation, it can be achieved following the [onAdImpression](https://docs.jwplayer.com/players/reference/advertising-events#onadimpression) event.
How can we achieve this ?

**Comment by Mr30nama** [comment]
+1

**Comment by chaimPaneth** [comment]
Hi, @DevineDecrypter @Mr30nama 

Check the latest version iv'e added an onAdEvent callback with those.

**Comment by chaimPaneth** [comment]
This was added in latest versions.

**Comment by DevineDecrypter** [comment]
Thanks for adding the onAdEvent, i tried to use it, i logged the event but it was very vague.
Is it possible for you to explain the usage of the event ?
