### ISSUE TITLE
Change only player's volume

### ISSUE THREAD

**Issue by Pardeep-Raman-Dmi** [chaimPaneth/react-native-jw-media-player#339]
Hi, we want to change the JW player volume only using the custom UI controls. But when we change the player's volume using setVolume method, it also changes the volume of the mobile device.
Please do let us know if we can fix this.
Thanks.

**Comment by StackZs** [comment]
> Hi, we want to change the JW player volume only using the custom UI controls. But when we change the player's volume using setVolume method, it also changes the volume of the mobile device. Please do let us know if we can fix this. Thanks.

did you solve this issue?
