### ISSUE TITLE
Get error 102630 with source video from youtube

### ISSUE THREAD

**Issue by PhamMinhKha** [chaimPaneth/react-native-jw-media-player#34]
I get youtube link download from youtube 
I have checked the path in my browser and it works
Link be like
`https://r3---sn-42u-i2i6.googlevideo.com/videoplayback?expire=1581370303&ei=X3dBXsOBA4mR4AL7kqnIBA&ip=150.95.114.172&id=o-AB4f5tYq_JBvnsi6hIUva2jS1sYN6S00h9Lz35NgPf7J&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-42u-i2i6%2Csn-42u-nbo6&ms=au%2Crdu&mv=u&mvi=2&pl=21&vprv=1&mime=video%2Fmp4&gir=yes&clen=14781074&ratebypass=yes&dur=315.628&lmt=1580882523007800&mt=1581348373&fvip=3&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHylml4wRAIgEXAiDymwQB4FzEQw2S21Snoa_Rw0kAoyKPtyxdpGTqQCIFAi2g3g75qShheNnuua2l3Qk_80NBQqx7ueQ2gSoDRY&sig=ALgxI2wwRQIhAIXrrCRXTbIZmsO8ZKRVtP8M3G9mewIBXOn6W4Yu94sEAiBIbXJPJjyLz-mNT32qtz74rkxrPoBwCm1AJbgZ6oQ3VQ==`
![Screen Shot 2020-02-10 at 10 33 17 PM](https://user-images.githubusercontent.com/12944689/74163940-ac028980-4c55-11ea-8ca8-e6dc7ea84e0d.png)
![Screen Shot 2020-02-10 at 10 36 09 PM](https://user-images.githubusercontent.com/12944689/74164067-db18fb00-4c55-11ea-8906-2b37262c5942.png)

**Comment by shelomo** [comment]
JW does not support Youtube files

**Comment by TfADrama** [comment]
> JW does not support Youtube files

I got this error only for android and using videos not from youtube but from somewhere else. In android i can only play videos that exist in my JWPlayer account. In iOS everything works, it is normal?

**Comment by chaimPaneth** [comment]
@TfADrama 

I'm not sure I understand your last comment, though please open a new issue regarding your last comment as the topic has shifted.

Closing this issue.
