### ISSUE TITLE
GoogleCast on iOS doesn't cast

### ISSUE THREAD

**Issue by Sccttt** [chaimPaneth/react-native-jw-media-player#350]
Issue: Failure to Cast Video from iOS Devices

Description:
I'm encountering an issue when attempting to cast videos from an iOS device. While the video plays seamlessly on the device itself, initiating a cast results in a successful connection without video playback.

To better illustrate the problem, I've recorded a demonstration using a simulator. It's important to note that the same issue persists on actual hardware.

Troubleshooting Attempts:

Conducted thorough debugging efforts without success.
Examined log files, which unfortunately did not yield any useful insights.

[Video Recording](https://github.com/chaimPaneth/react-native-jw-media-player/assets/6411465/639565f7-8354-4dc3-b120-b4546f854878)

I would deeply appreciate any guidance or insights that could help resolve this casting issue. Thank you.

**Comment by Jmilham21** [comment]
See work for this issue [here](https://github.com/chaimPaneth/react-native-jw-media-player/pull/352)

**Comment by Sccttt** [comment]
Perfect! Thank you!!
