### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by TfADrama** [chaimPaneth/react-native-jw-media-player#40]
Executing the example project gives an error in iOS:

> Ordered comparison between pointer and zero ('NSNumber *' and 'int')
In line 32 of file RCJavaScriptLoader.mm

Android is not working too...

> TypeError: Cannot read property 'message' of undefined
    at handleError (/Users/.../Documents/Demos/react-native-jw-media-player-master/Example/node_modules/react-native/local-cli/cliEntry.js:35:21)

**Comment by chaimPaneth** [comment]
Iv'e updated the example and tested it, it's working now.

Thank you.
