### ISSUE TITLE
Playlist in Android not working 

### ISSUE THREAD

**Issue by TfADrama** [chaimPaneth/react-native-jw-media-player#41]
I made a playlist with playlistItems and in iOS worked, Android don't. 
Am i missing something? Or it's a feature to add in the feature?

**Comment by chaimPaneth** [comment]
@TfADrama can you try latest version 0.1.42 and check if it's working?

**Comment by chaimPaneth** [comment]
Closing to inactivity - should work since version 0.1.42 and up.

**Comment by dalbeerworksdelight** [comment]
@chaimPaneth I have tried 0.1.42 and so on versions but in android playlist is not working

**Comment by dalbeer22g** [comment]
@chaimPaneth I have tried versions 0.1.42 and so on but playlist is not working on android

**Comment by hapo-vupq** [comment]
@dalbeer22g Current version is 0.1.48, you can update to resolve your problem.

**Comment by MohitDhingra0786** [comment]
> @dalbeer22g Current version is 0.1.48, you can update to resolve your problem.

I have updated but still not working

**Comment by dalbeer22g** [comment]
@hapo-vupq i have updated to latest version still not working. Can you please help me a little more by providing code or little more information.
