### ISSUE TITLE
Android video is black after going in/out fullscreen

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#48]
Latest version used 
0.1.40

On android going into full screen mode video is black screen. Audio still playing normally. After seeking into other time or pressing settings & back video is shown again. Sometimes same thing replicated on going back out of full screen.

EDIT: play/pause also helps

**Comment by chaimPaneth** [comment]
Hi @KestasVenslauskas 

Can you check the latest version 0.1.41 if this still happens?

I was using some code referenced in the jwplayer best practice android apps that was meant to prevent the media coders from crashing but that resulted in the black screen, I removed it and it's working for me but I'm not sure if this will result in the media coders crashing as mentioned so please check it out.

Thanks

**Comment by KestasVenslauskas** [comment]
Will get back to you on my apps next release

**Comment by KestasVenslauskas** [comment]
can confirm that it's fixed in 0.1.41
