### ISSUE TITLE
How can i use video with ads in multiple video list?

### ISSUE THREAD

**Issue by codal-mpawar** [chaimPaneth/react-native-jw-media-player#5]

**Comment by panchalsanket** [comment]
Can you please send me your working code?

**Comment by codal-mpawar** [comment]
i m done with this problem thank you

**Comment by codal-mpawar** [comment]
have you known about this error?

Exception in thread "main" java.lang.IllegalStateException: Expected a load for F to set up parameter 9 for com/longtailvideo/jwplayer/core/b/b$$Lambda$0 but got -1
        at com.google.common.base.Preconditions.checkState(Preconditions.java:756)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.attemptAllocationBeforeArgumentLoads(LambdaDesugaring.java:543)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:427)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1623)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

Exception in thread "main" java.lang.IllegalStateException: Expected a load for Ljava/lang/String; to set up parameter 1 for com/longtailvideo/jwplayer/core/a/a$$Lambda$0 but got -1
        at com.google.common.base.Preconditions.checkState(Preconditions.java:756)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.attemptAllocationBeforeArgumentLoads(LambdaDesugaring.java:543)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:427)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1623)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/26.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/89.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/104.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/76.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/91.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/63.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/78.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/33.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/48.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/46.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/61.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/22.jar --input /Users/codal/Documents/projects/flexAds/node_modules/react-native-image-picker/android/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/8.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/28.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/43.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/79.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/94.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/40.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/55.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/30.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/66.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/81.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/49.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/64.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/62.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/77.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/58.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/73.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/88.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/103.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/45.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/60.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/78.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/93.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/95.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/110.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/90.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/105.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/20.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/74.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/89.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/94.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/109.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/31.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/46.jar --input /Users/codal/Documents/projects/flexAds/node_modules/react-native-vector-icons/android/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/13.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/48.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/63.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/47.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/62.jar --input /Users/codal/Documents/projects/flexAds/node_modules/react-native-firebase/android/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/2.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/64.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/79.jar --input /Users/codal/Documents/projects/flexAds/node_modules/react-native-splash-screen/android/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/12.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/91.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/106.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/27.jar --input /Users/codal/Documents/projects/flexAds/node_modules/react-native-share/android/build/intermediates/intermediate-jars/debug/classes.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/10.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/15.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/49.jar --input /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/73.jar --output /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/desugar/debug/88.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-jw-media-player/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/@endemolshinegroup/react-native-video-with-ads/android-exoplayer/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-firebase/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/@synapsestudios/react-native-zendesk-support/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-fetch-blob/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-social-share/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-google-places/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-image-resizer/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-image-picker/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-fs/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-share/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-facebook-login/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-splash-screen/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/node_modules/react-native-vector-icons/android/build/intermediates/intermediate-jars/debug/classes.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/classes/debug --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/0.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/1.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/2.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/3.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/4.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/5.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/6.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/7.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/8.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/9.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/10.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/11.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/12.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/13.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/14.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/15.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/16.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/17.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/18.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/19.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/20.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/21.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/22.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/23.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/24.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/25.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/26.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/27.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/28.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/29.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/30.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/31.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/32.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/33.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/34.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/35.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/36.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/37.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/38.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/39.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/40.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/41.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/42.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/43.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/44.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/45.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/46.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/47.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/48.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/49.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/50.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/51.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/52.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/53.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/54.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/55.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/56.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/57.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/58.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/59.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/60.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/61.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/62.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/63.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/64.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/65.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/66.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/67.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/68.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/69.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/70.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/71.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/72.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/73.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/74.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/75.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/76.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/77.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/78.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/79.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/80.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/81.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/82.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/83.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/84.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/85.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/86.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/87.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/88.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/89.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/90.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/91.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/92.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/93.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/94.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/95.jar --classpath_entry /Users/codal/Documents/projects/flexAds/android/app/build/intermediates/transforms/stackFramesFixer/debug/96.jar --classpath_entry /Users/codal/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value-annotations/1.6/da725083ee79fdcd86d9f3d8a76e38174a01892a/auto-value-annotations-1.6.jar --classpath_entry /Users/codal/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.7/751f548c85fa49f330cecbb1875893f971b33c4e/gson-2.7.jar --bootclasspath_entry /Users/codal/Library/Android/sdk/platforms/android-27/android.jar --bootclasspath_entry /Users/codal/Library/Android/sdk/platforms/android-27/optional/org.apache.http.legacy.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/resources.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/rt.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jsse.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jce.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/charsets.jar --bootclasspath_entry /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jfr.jar --min_sdk_version 21 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes --legacy_jacoco_fix}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

react-native version 
"react-native": "0.57.8",

gradle version
classpath 'com.android.tools.build:gradle:3.1.4'

help me to solve error plz...

**Comment by panchalsanket** [comment]
No, I am getting Black screen

**Comment by codal-mpawar** [comment]
@panchalsanket @chaimPaneth  
hey,
have you known in JWPlayer autostart, repeat, desc all the props are not working in android and how can I manage in Flat list in multiple video pause and play at the same time?
so please solve this and comment to me as fast as possible.

**Comment by codal-mpawar** [comment]
@panchalsanket which document you follow?

**Comment by chaimPaneth** [comment]
Hi @codal-mpawar, can you attach some of your code, also send me your gradle settings - you might need to play around with the versions of target compile build and support sdk's / libraries.

As for the play pause of multiple videos in a list I guess for now you will have to create a dynamic ref for each item based on it's index in the data map something like ref={p => this["player_" + index = p]} and call this.[itemRef].play() etc.

**Comment by codal-mpawar** [comment]
Hi @chaimPaneth  
yes, I already do that but not working. also in iOS, multiple videos are not working on a single screen. so can you please solve this and let me know. I solve all the gradle stuff.

**Comment by chaimPaneth** [comment]
Hi @codal-mpawar

Can you please try the latest version 0.1.15 there is a fix in there that should fix the multiple instances crash.
