### ISSUE TITLE
Request for additional callbacks

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#51]
Requesting few more callbacks:
`onComplete` - when media has reached the ending.
`onSeek` - when seek was requested from default controls.

Isn't `onIdle` the same as my requested `onComplete`? If so it does not work android.

Also `onTime` callback does not return described parameters (checked android).

**Comment by chaimPaneth** [comment]
@KestasVenslauskas onComplete is implemented, I will get to the rest once I have more time - help is appreciated :-)

I will check out onTime on android as well.

**Comment by chaimPaneth** [comment]
@KestasVenslauskas I've merged https://github.com/chaimPaneth/react-native-jw-media-player/pull/52 for onTime fix.

Thanks to @kononenkoAnton

**Comment by KestasVenslauskas** [comment]
@chaimPaneth @kononenkoAnton The thing with onTime is that I still can't see the given data in the callback event.
I did the same approach yesterday to check if that would work so I would made a PR myself.
Am I missing something here? Look at the screenshot
https://prnt.sc/scgtb8

**Comment by chaimPaneth** [comment]
Try 

```
onTime(e) {
    var {position, duration} = e.nativeEvent
    console.log(position, duration)
}
```

Does this work?

**Comment by KestasVenslauskas** [comment]
@chaimPaneth It works! Forgot it's under nativeEvent prop... Omg sry I'm fairly new to RN things :)
BTW added few PR's also

**Comment by chaimPaneth** [comment]
I merged your PR's thanks.
