### ISSUE TITLE
Prop 'adSchedule' on iOS and Android not working.

### ISSUE THREAD

**Issue by hapo-vupq** [chaimPaneth/react-native-jw-media-player#58]
When I run app with this code, i see black dot at 10s in seek bar but when the video runs to the black dot, my Ads not running.
And this is link VAST xml file: 
https://xxxxxx/vast/?zone=24

Thanks for reading my issue, sorry because my English is bad.

**Comment by chaimPaneth** [comment]
@JanSunavec can you help out here I've used the code in your PR https://github.com/chaimPaneth/react-native-jw-media-player/pull/38 for adSchedule.

Thanks

**Comment by JanSunavec** [comment]
You need to use        
{
        mediaId: "1",
        title: "asd",
        desc: "desc",
        time: 0,
        file: "my.mp4",
        autostart: true,
        controls: true,
        repeat: false,
        displayDescription: true,
        displayTitle: true,
        schedule: [{offset: "", tag: ""}]
}

**Comment by chaimPaneth** [comment]
Hi @JanSunavec thanks for helping ou.

I've renamed the prop `schedule` to adSchedule` in my merge and @hapo-vupq is using it as intended perhaps there is an issue with the tag url? I don't know as I'm not showing ads as of now in my apps, any idea?

**Comment by hapo-vupq** [comment]
Oh, sorry, it working on Android and not working on iOS.
I test again and see Ads running on Android.
@JanSunavec schedule: [{offset: "", tag: ""}] not is a prop. 😄

**Comment by tuan1192** [comment]
> @JanSunavec can you help out here I've used the code in your PR #38 for adSchedule.
> 
> Thanks

Thank you for your update, on Android seem worked, but on iOS still not working.

**Comment by simonemarinelli** [comment]
When I set `adSchedule` I get this error message on iOS:

```
Error: Google IMA has been requested without having imported its Framework.
If you do not wish to import the Google IMA framework, you may use JWPlayer's Vast Plugin to play ads by setting your adClient to vastPlugin.
For more information visit JWAdConfig.h.
```

**Comment by pqv2210** [comment]
Hi @simonemarinelli, I changed all 'JWAdClientGoogima' to 'JWAdClientVast' in RNJWPlayerNativeView.m and my ADS run on iOS. You can try it.
Good luck!

**Comment by simonemarinelli** [comment]
Hi @pqv2210 thanks for your reply I changed all 'JWAdClientGoogima' to 'JWAdClientVast' like you said. Now I can see the dots on the seek bar but the ads still not playing.

**Comment by simonemarinelli** [comment]
Hi @pqv2210 my bad I had a broken VAST tag. Now I fixed the issue. Thanks a lot it works.

**Comment by simonemarinelli** [comment]
I noticed that sometimes when I play videos the ads is loaded but it blocks.
This is the output I get on Xcode debugger console.

```bash
 [assertion] Error acquiring assertion: <NSError: 0x2800b61f0; domain: RBSAssertionErrorDomain; code: 2; reason: "Client is missing required entitlement"> {
    userInfo = {
        RBSAssertionAttribute = <RBSLegacyAttribute: 0x145d72820; requestedReason: MediaPlayback; reason: MediaPlayback; flags: PreventTaskSuspend | PreventTaskThrottleDown | WantsForegroundResourcePriority>;
    }
}
```

**Comment by pqv2210** [comment]
@simonemarinelli, I have never encountered this error but I have run ads on my real ios device and here is an example:
adSchedule:
  [{
    tag: 'https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0',
    offset: '10',
  }],
If you can't run it, please leave a comment. Thanks! 😀

**Comment by simonemarinelli** [comment]
@pqv2210 with your VAST it works.

**Comment by hapo-vupq** [comment]
@simonemarinelli Can you send me url your VAST with error above? Tkanks.

**Comment by pqv2210** [comment]
@simonemarinelli Can you send me url your VAST with error above? Tkanks.

**Comment by simonemarinelli** [comment]
@pqv2210 Yes sure, here is it!
`https://secure.adnxs.com/ptv?id=14461029&kw_position=instream,pre-roll&kw_adnz_adpreview=test`

**Comment by pqv2210** [comment]
@simonemarinelli i checked your VAST URL and i think in MediaFile, maybe iOS not support for video has the .js extension, you can try with video has the .mp4 extension. :D
