### ISSUE TITLE
onSeek & onSeeked iOS callbacks

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#59]
onSeek & onSeeked event callbacks on iOS is not working. Would love to implement it myself but at this moment my objective c skills are not enough :/

**Comment by chaimPaneth** [comment]
@KestasVenslauskas check the latest version I've put it in tell me of it works

**Comment by KestasVenslauskas** [comment]
0.1.45 does not work as expected
onSeek works but gives wrong data example `{"target": 6243}` where 6243 is the length of the video instead of possition.
onSeeked does not work at all which I require mostly because on Android onSeeked event callback comes after successful seek where onSeek if called before this action.

**Comment by KestasVenslauskas** [comment]
Also this may be the problem
```
-(void)onRNJWPlayerSeek:(JWEvent<JWSeekEvent> *)event;
-(void)onRNJWPlayerSeeked:(JWEvent<JWSeekEvent> *)event;
```

Both using `JWSeekEvent` but I think  `onRNJWPlayerSeeked` should use `JWSeekedEvent`
Anyway this is how it works on android

**Comment by chaimPaneth** [comment]
Ah yes perhaps your right I'll check later

**Comment by chaimPaneth** [comment]
I've pushed some changes to latest version with correct data for seek event and seeked event doesn't have any data in iOS but it exists, check it out.

Thanks

**Comment by chaimPaneth** [comment]
@KestasVenslauskas can I close this issue?

**Comment by KestasVenslauskas** [comment]
Yes tank you!
