### ISSUE TITLE
when chromecast support?

### ISSUE THREAD

**Issue by StarDev0308** [chaimPaneth/react-native-jw-media-player#61]
I am implementing JWPlayer on my RN app.
It's working well but unfortunately, seems it is not supported for chromecast.

If someone knows that, I am appreciate.

Thanks

**Comment by chaimPaneth** [comment]
Closing in favor of https://github.com/chaimPaneth/react-native-jw-media-player/issues/31

**Comment by StarDev0308** [comment]
Hey, chaimPaneth

why are you closing this question?

I am not sure.
