### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by olivinesguerra** [chaimPaneth/react-native-jw-media-player#62]
Hi. Is there any way we could control the volume or mute?

Thanks

**Comment by chaimPaneth** [comment]
Hi @olivinesguerra I haven't implemented this yet, I might get around to this in a while, any PR's are appreciated.

**Comment by chaimPaneth** [comment]
@olivinesguerra I didn't see a native method on the jwplayer that allows setting the volume, there is only an option to mute the player but the actual volume I think the user has to set with the device's controls.

Can you recheck the docs I might have missed it.

Thanks.

**Comment by arsimr16** [comment]
https://github.com/chaimPaneth/react-native-jw-media-player/pull/105

This has been merged and adds support for muting.
