### ISSUE TITLE
CHANGELOG.md or Release Notes

### ISSUE THREAD

**Issue by curtisbelt** [chaimPaneth/react-native-jw-media-player#64]
Hello, I don't see any easy way to see what's changed between versions. Can you let me know if I've missed that somewhere? Otherwise I do recommend keeping a CHANGELOG.md or tagging your releases on Github w/ accompanying documentation. Appreciate your work!

**Comment by chaimPaneth** [comment]
@curtisbelt for now I started adding release notes check out https://github.com/chaimPaneth/react-native-jw-media-player/releases

Thanks
