### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by PierreCapo** [chaimPaneth/react-native-jw-media-player#66]
@chaimPaneth before starting, thanks a lot for your library! We are currently using it in our team, and your work helped us a lot!

Since we are using Typescript, we added a basic typescript definition in our project but I've figured that I could spend more time to make it exhaustive and open a PR here. Are you encline to have and maintain typescript definition in this repo ? As I said I can open a PR to add typescript definitions for the current API.

Cheers!

**Comment by chaimPaneth** [comment]
Hi @PierreCapo thanks for your feedback! and yes I'de be happy if you could open that PR for Typescript definition, I just never got around to it...

Thanks.

**Comment by PierreCapo** [comment]
Nice!  I close this issue in favor of https://github.com/chaimPaneth/react-native-jw-media-player/pull/67
