### ISSUE TITLE
Android Fullscreen Bound to Parent Container

### ISSUE THREAD

**Issue by BeshoySarkis** [chaimPaneth/react-native-jw-media-player#7]
When clicking on the fullscreen button, the app changes orientation but does not take over the display. It appears that the player goes into fullscreen of the container that it is in, rather than taking over the screen.

We invoke the player using
`const playlistItem = {
    file: 'sample.com',
    mediaId: 'sample',
    autostart: false
}`

                <JWPlayer
                    playlistItem={playlistItem}
                    style={styles.player}
                    onBeforePlay={() => this.printSomething("onBeforePlay", null)}
                    onPlay={() => this.printSomething("onPlay", null)}
                    onPause={() => this.printSomething("onPause", null)}
                    onIdle={() => this.printSomething("onIdle", null)}
                    onPlaylistItem={event => this.printSomething("onPlaylistItem", event)}
                    onSetupPlayerError={event => this.printSomething("onSetupPlayerError",event)}
                    onPlayerError={event => this.printSomething("onPlayerError", event)}
                    onBuffer={() => this.printSomething("onBuffer", null)}
                    onFullScreen={() => this.onFullScreen()}
                    onPlayerReady={() => this.onPlayerReady()}
                    onFullScreenExit={() => this.onFullScreenExit()}
                />
RN version: 0.57.4
JWPlayer: 3.7.0
react-native-jw-media-player: 0.1.12

**Comment by chaimPaneth** [comment]
Hi @BeshoySarkis 

As of now the package only notifies the js that a fullscreen style was requested by the user in the onFullScreen callback and you need to manage the state of the player so when so it changes the parent view bounds to full height & width when fullscreen equals true.

We will work on a native fullscreen solution in the future.

Thanks.

**Comment by BeshoySarkis** [comment]
Thanks!
