### ISSUE TITLE
How to remove button Rewind 10 seconds in control bar?

### ISSUE THREAD

**Issue by pqv2210** [chaimPaneth/react-native-jw-media-player#71]
I tried remove button rewind 10 seconds by change skin JWP but look like prop playerStyle doesn't work, or native not receive css file. 😭

**Comment by chaimPaneth** [comment]
Hi @pqv2210  did you put the css file in the assets folder or in the root dir for iOS and pass the name of the file to playerStyle prop without the filetype for instance "myCss.css" you only pass `playerStyle={"myCss"}` also is your css file properly defining the theme with filename preceding every tag - can you share an example?

Thanks

**Comment by hapo-vupq** [comment]
Hi @chaimPaneth I put .css file be like this image
![example](https://user-images.githubusercontent.com/64763689/86996775-b3af6580-c1d6-11ea-83f2-46f429b7bd72.png)
And this is myCss.css file.
.jwplayer.jw-skin-myCss.jw-state-idle .jw-controls {
    background: rgba(255, 255, 255, .7);
  }
  
  /* Round, white play & restart buttons with black icons */
  .jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container,
  .jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container {
    background-color: white;
    border-radius: 50%;
    width: 100px;
    height: 100px;
  }
  
  .jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container .jw-icon,
  .jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container .jw-icon {
    color: #1E1E1E;
    width: 60px;
    height: 60px;
    padding: 20px;
  }
  
  /* Change play button colors on idle state, handle hover transitions */
  .jwplayer.jw-skin-myCss.jw-state-idle .jw-display-controls .jw-display-icon-container {
    background-color: #e5322c;
    height: 80px;
    width: 80px;
    -webkit-transition: -webkit-transform 0.35s;
    transition: transform 0.35s;
  }
  
  .jwplayer.jw-skin-myCss.jw-state-idle .jw-display-controls .jw-display-icon-container .jw-icon {
    color: #fff;
    height: 40px;
    width: 40px;
    padding: 20px;
  }  
  
  /* Customize font style and positioning for titles */
  .jwplayer.jw-skin-myCss.jw-state-idle .jw-title {
    height: 100%;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
  }
  
  /* Change colors and remove gradient shadow for control bar, change icon color on pause */
  .jwplayer.jw-skin-myCss .jw-display {
    padding-bottom: 45px;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar {
    background-color: #fff;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-button-container .jw-button-color {
    color: #1E1E1E;
  }
  
  .jwplayer.jw-skin-myCss.jw-state-paused .jw-controlbar .jw-button-container .jw-button-color {
    color: #e5322c;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-button-container .jw-button-color:hover {
    color: #92DCE5;
  }
  
  
  /* Move tooltips closer to control bar with inline timeslider, change colors, round corners, remove shadow */
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip {
    bottom: 70%;
    box-shadow: none;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip.jw-open {
    border-radius: 5px;
    color: #92DCE5;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip .jw-text {
    background-color: #92DCE5;
    border-radius: 5px;
    border: 0;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-text {
    color: #1E1E1E;
  }  
  
  /* Customize colors of volume control knob */
  .jwplayer.jw-skin-myCss .jw-overlay .jw-slider-volume .jw-slider-container .jw-knob {
    background-color: #e5322c;
  }
  
  
  /* Customize colors of timeslider */
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-rail {
    background-color: #1E1E1E;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-buffer {
    background-color: #92DCE5;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-progress {
    background-color: #e5322c;
  }
  
  .jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-knob {
    background-color: #e5322c;
  }
  
  
  /* Customize colors/opacity of the settings menu */
  .jwplayer.jw-skin-myCss .jw-settings-menu {
    background-color: transparent;
  }
  
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-topbar {
    background-color: #92DCE5;
  }
  
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-topbar .jw-icon:hover {
    color: #1E1E1E;
  }
  
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-submenu {
    background-color: rgba(0, 0, 0, 1);
  }
  
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-content-item {
    color: #1E1E1E;
  }
  
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-content-item:hover,
  .jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-item-active {
    color: #e5322c;
    font-weight: bold;
  }

**Comment by pqv2210** [comment]
Hi @chaimPaneth I put .css file be like this image
![example](https://user-images.githubusercontent.com/32980987/87002714-6afea900-c1e4-11ea-9252-d58a071a6a02.png)
And this is myCss.css file.
.jwplayer.jw-skin-myCss.jw-state-idle .jw-controls {
background: rgba(255, 255, 255, .7);
}

/* Round, white play & restart buttons with black icons */
.jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container,
.jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container {
background-color: white;
border-radius: 50%;
width: 100px;
height: 100px;
}

.jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container .jw-icon,
.jwplayer.jw-skin-myCss .jw-display-controls .jw-display-icon-container .jw-icon {
color: #1E1E1E;
width: 60px;
height: 60px;
padding: 20px;
}

/* Change play button colors on idle state, handle hover transitions */
.jwplayer.jw-skin-myCss.jw-state-idle .jw-display-controls .jw-display-icon-container {
background-color: #e5322c;
height: 80px;
width: 80px;
-webkit-transition: -webkit-transform 0.35s;
transition: transform 0.35s;
}

.jwplayer.jw-skin-myCss.jw-state-idle .jw-display-controls .jw-display-icon-container .jw-icon {
color: #fff;
height: 40px;
width: 40px;
padding: 20px;
}

/* Customize font style and positioning for titles */
.jwplayer.jw-skin-myCss.jw-state-idle .jw-title {
height: 100%;
display: flex;
justify-content: center;
flex-direction: column;
align-items: center;
}

/* Change colors and remove gradient shadow for control bar, change icon color on pause */
.jwplayer.jw-skin-myCss .jw-display {
padding-bottom: 45px;
}

.jwplayer.jw-skin-myCss .jw-controlbar {
background-color: #fff;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-button-container .jw-button-color {
color: #1E1E1E;
}

.jwplayer.jw-skin-myCss.jw-state-paused .jw-controlbar .jw-button-container .jw-button-color {
color: #e5322c;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-button-container .jw-button-color:hover {
color: #92DCE5;
}

/* Move tooltips closer to control bar with inline timeslider, change colors, round corners, remove shadow */
.jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip {
bottom: 70%;
box-shadow: none;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip.jw-open {
border-radius: 5px;
color: #92DCE5;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-tooltip .jw-text {
background-color: #92DCE5;
border-radius: 5px;
border: 0;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-text {
color: #1E1E1E;
}

/* Customize colors of volume control knob */
.jwplayer.jw-skin-myCss .jw-overlay .jw-slider-volume .jw-slider-container .jw-knob {
background-color: #e5322c;
}

/* Customize colors of timeslider */
.jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-rail {
background-color: #1E1E1E;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-buffer {
background-color: #92DCE5;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-progress {
background-color: #e5322c;
}

.jwplayer.jw-skin-myCss .jw-controlbar .jw-slider-time .jw-slider-container .jw-knob {
background-color: #e5322c;
}

/* Customize colors/opacity of the settings menu */
.jwplayer.jw-skin-myCss .jw-settings-menu {
background-color: transparent;
}

.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-topbar {
background-color: #92DCE5;
}

.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-topbar .jw-icon:hover {
color: #1E1E1E;
}

.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-submenu {
background-color: rgba(0, 0, 0, 1);
}

.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-content-item {
color: #1E1E1E;
}

.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-content-item:hover,
.jwplayer.jw-skin-myCss .jw-settings-menu .jw-settings-item-active {
color: #e5322c;
font-weight: bold;
}

**Comment by chaimPaneth** [comment]
@pqv2210 I used this css file and my player successfully changed the style.

Try defining the playerStyle param on the player object and on the playlistItem object as so:

```
<JWPlayer
          ref={p => (this.JWPlayer = p)}
          style={styles.player}
          playerStyle={"myCss"} // <- here
          playlistItem={{
            playerStyle: "myCss", // <- and here
            file,
            title,
            mediaId,
            image,
            desc,
            autostart,
            controls,
            repeat,
            displayDescription,
            displayTitle
          }}
          autostart={autostart}
          nativeFullScreen={true}
          fullScreenOnLandscape={fullScreenOnLandscape}
          onPlay={this.onPlay}
          onPause={this.pause}
          onTime={this.onTime}
          onFullScreen={this.openFullScreen}
          onFullScreenExit={this.closeFullScreen}
          onPlaylistItem={this.onPlaylistItem}
          onPlayerReady={this.onPlayerReady}
          onComplete={this.onComplete}
          onSetupPlayerError={this.onError}
          onPlayerError={this.onError}
        />
``` 

Also make sure that when you select the file in xcode your project is check marked as the Target Membership for the file.

**Comment by hapo-vupq** [comment]
@chaimPaneth Thank you so much, it is working.
I see a function removeButton in https://sdk.jwplayer.com/android/v3/reference/index.html?com/longtailvideo/jwplayer/JWPlayerView.html and I can't find id of rewind button.
Can you find id of button?

**Comment by pqv2210** [comment]
@chaimPaneth Thank you so much, it is working.
I see a function removeButton in https://sdk.jwplayer.com/android/v3/reference/index.html?com/longtailvideo/jwplayer/JWPlayerView.html and I can't find id of rewind button.
Can you find id of button?

**Comment by chaimPaneth** [comment]
@pqv2210 

The removeButton function is only meant to remove custom buttons that you added using the addButton function https://sdk.jwplayer.com/android/v3/reference/com/longtailvideo/jwplayer/JWPlayerView.html#addButton-java.lang.String-java.lang.String-com.longtailvideo.jwplayer.events.listeners.VideoPlayerEvents.OnCustomButtonClickListener-java.lang.String-java.lang.String- 

Closing this issue now.
