### ISSUE TITLE
Display image with video extension .m3u8

### ISSUE THREAD

**Issue by hapo-vupq** [chaimPaneth/react-native-jw-media-player#73]
Hi @chaimPaneth ,
I have a url with extension .m3u8 (no video, it is black screen), and i want display image by 'image' prop in playListItem when my video url black screen. Android done, but iOS not working...
Can you tell me how to do it? :((
Thank you!

**Comment by chaimPaneth** [comment]
@hapo-vupq this should be similar on iOS, what's the url you're passing for android image?

**Comment by hapo-vupq** [comment]
@chaimPaneth I pass a url extension .jpg be like
https://cdn.britannica.com/84/73184-004-E5A450B5/Sunflower-field-Fargo-North-Dakota.jpg

**Comment by chaimPaneth** [comment]
Hi @hapo-vupq I used the image url you attached above and it's working fine for me. Can you show me the code how you define the image for the `playlistItem`. Thanks.

![Simulator Screen Shot - iPhone 11 Pro - 2020-07-31 at 18 17 33](https://user-images.githubusercontent.com/20083971/89049777-6a2be380-d35a-11ea-8355-e1acaf90e53c.png)

**Comment by hapo-vupq** [comment]
@chaimPaneth this is my example ...
`playlistItem={{
              mediaId: '1',
              file: 'https://wse.hatinhtv.net/audio/recorded2020-08-12_6.mp4/playlist.m3u8',
              autostart: true,
              controls: true,
              image: 'https://cdn.britannica.com/84/73184-004-E5A450B5/Sunflower-field-Fargo-North-Dakota.jpg',
            }}`

**Comment by hapo-vupq** [comment]
@chaimPaneth This is my example.
```
playlistItem={{
  mediaId: '1',
  file: 'https://wse.hatinhtv.net/audio/recorded2020-08-12_6.mp4/playlist.m3u8',
  autostart: true,
  controls: true,
  image: 'https://cdn.britannica.com/84/73184-004-E5A450B5/Sunflower-field-Fargo-North-Dakota.jpg'
}}
```

**Comment by hapo-vupq** [comment]
@chaimPaneth Can you give me your example?
Thank you!

**Comment by hapo-vupq** [comment]
@chaimPaneth Hi, i using ver 0.1.46 and i can't show image with video .m3u8 with iOS.
I upgrade JWPlayer-SDK to 3.16.0 but not work.
Can you show me how to display image with ver 0.1.46?
Thank you!

**Comment by hapo-vupq** [comment]
Done!
My fault, i update version SDK and set controls: true.
