### ISSUE TITLE
Does this library support video casting

### ISSUE THREAD

**Issue by srinivaassunil** [chaimPaneth/react-native-jw-media-player#78]
JW player provides casting in the native library. But I don't see any [method ](https://developer.jwplayer.com/jwplayer/docs/android-enable-casting-to-chromecast-devices)to access it. Please help.

**Comment by srinivaassunil** [comment]
Managed this using [react-native-google-cast](https://github.com/react-native-google-cast/react-native-google-cast) .

**Comment by chaimPaneth** [comment]
@srinivaassunil I'm adding jwplayer [casting](https://support.jwplayer.com/articles/how-to-enable-casting-and-airplay#:~:text=To%20enable%20casting%20for%20a,SDK%20or%20iOS%20SDK%20directly.&text=From%20your%20list%20of%20players,click%20the%20toggle%20to%20ON). in the next version, it will be ready in the next few days.

**Comment by chaimPaneth** [comment]
This was added in latest versions.
