### ISSUE TITLE
Android Breaks with JW Player SDK version 3.16.0 

### ISSUE THREAD

**Issue by DrCorduroy** [chaimPaneth/react-native-jw-media-player#79]
JWPlayer Android SDK 3.16.0 Release Notes:
Updated the Google IMA to support version 3.18.1.

This has caused some sort of incompatibility between google packages. It wasn't able to find androidx.media.session.

<s>Downgrading to 3.15.1 fixed the issue.</s>

**Comment by alexwasner** [comment]
I'm guessing I have a similar issue. I'm not sure how it could be related, but my android builds started failing last night and it seems like jetify isn't converting them to `androidx` for me anymore. I tried building via CircleCI on the same commit that succeeded and it failed, so it's something external to my codebase.

Tons of errors like this: 
```
node_modules/react-native-jw-media-player/android/src/main/java/com/appgoalz/rnjwplayer/NotificationWrapper.java:10: error: package android.support.v4.media does not exist
import android.support.v4.media.MediaDescriptionCompat;
```

**Comment by DrCorduroy** [comment]
I spoke too soon, not working for me.

I was able to build but now I'm getting a blank screen where the player should be. 

Yes, I was getting similar errors as yours.

Still working on it, will update.

**Comment by mYmEvrei** [comment]
same

**Comment by Minishlink** [comment]
In the mean time you can use this patch (apply with patch-package) https://gist.github.com/Minishlink/180e03aebd28b5071b40f75d1d90e73d

**Comment by mYmEvrei** [comment]
@Minishlink  Thank you, I am very grateful to you

**Comment by KestasVenslauskas** [comment]
You can also add `implementation 'androidx.media:media:1.1.0'`
instead downgrading jw player version.
Add it in react-native-jw-media-player android projects gradle file.
