### ISSUE TITLE
Attempt to invoke virtual method 'com...SessionManager.getCurrentCastSession()' on a null object reference

### ISSUE THREAD

**Issue by cmcaboy** [chaimPaneth/react-native-jw-media-player#85]
I have the latest version installed and I am receiving the following error on Android. Seems to be related to casting.

![image](https://user-images.githubusercontent.com/1489169/91914403-f7c66000-ec85-11ea-82ea-1492dcc124e5.png)

**Comment by cmcaboy** [comment]
If I downgrade to 2b28bd22929c327f2a1979ddd8617be641ebad01, the issue does not occur.

**Comment by power-cut** [comment]
same here but on android !!

**Comment by power-cut** [comment]
@cmcaboy @chaimPaneth any idea how to resolve this in android ??

**Comment by cmcaboy** [comment]
@power-cut I received the error on Android. I wasn't really able to dive into a solution so I ended up just downgrading to a stable version.

**Comment by maitzeth** [comment]
Im facing this issue too, but I need all the new features from the new version, I dont want to downgrade :(

**Comment by cmcaboy** [comment]
@maitzeth Although not ideal, you could fork the repo and manually add the new features from the newer versions. This can get tricky, but if the feature set you need is small, this could work.

**Comment by chaimPaneth** [comment]
This issue is fixed on the latest version 0.1.52.
