### ISSUE TITLE
Multiple videos cause app crash on iOS

### ISSUE THREAD

**Issue by BeshoySarkis** [chaimPaneth/react-native-jw-media-player#9]
When rendering multiple videos on a single page, the iOS app crashes.

Thread 1: EXC_BAD_ACCESS (code=1, address=0x222dfde48)

RN version: 0.59.4
JWPlayer: 3.7.0
react-native-jw-media-player: 0.1.12

**Comment by chaimPaneth** [comment]
Hi @beshoySarkis

Can you please try the latest version 0.1.15 there is a fix in there that should fix the multiple instances crash.

**Comment by BeshoySarkis** [comment]
Thank you

**Comment by BeshoySarkis** [comment]
I don't believe this library still supports playing multiple instances on a single page. There seems to be some clobbering of the instance of the player when multiple instances start up and player.stop() does not stop the first video which was rendered because it has a different reference than when it was started.

**Comment by BeshoySarkis** [comment]
This has been fixed in 0.1.22, resolving
