### ISSUE TITLE
NSMicrophoneUsageDescription info.plist error

### ISSUE THREAD

**Issue by KestasVenslauskas** [chaimPaneth/react-native-jw-media-player#90]
Hi after upgrading to a newest version 0.1.49 and adding everything required by casting I receive this email from apple:
`...The app's Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string...`
Should this be mentioned in readme ?
And why does it need a microphone usage?

**Comment by chaimPaneth** [comment]
I updated the readme in the next release. Thank you.

**Comment by KestasVenslauskas** [comment]
But isn't this missleading for user I mean why would casting require microphone? From which library it's required I need to inform my customer
