### ISSUE TITLE
Forward Controls not working

### ISSUE THREAD

**Issue by archcorsair** [chaimPaneth/react-native-jw-media-player#96]
Hello! Thank you for the wonderful project!

I am integrating this into my project and running into an issue. The issue is that while the rewind button appears, the fast forward button does not appear for me.
I have tested this on both Android and iOS, with `controls` turned both `on` and `off`.

Any ideas on what I might be doing wrong? Any information I can provide you to help debug this?

Thanks again!

**Comment by chaimPaneth** [comment]
@archcorsair do you mean the 10 seconds rewind button I think the default template of player only includes a 10 second back button you will need to customize the player theme to add a forward button. 

Can you look into that?

Thanks

**Comment by archcorsair** [comment]
@chaimPaneth I don't understand the the API as well as you, but I did notice that the forward skip 10 seconds button code exists.

https://github.com/chaimPaneth/react-native-jw-media-player/blob/master/ios/RNJWPlayerControls.m#L45
https://github.com/chaimPaneth/react-native-jw-media-player/blob/master/ios/RNJWPlayerControls.m#L147

Any pointers would be greatly appreciated.

**Comment by chaimPaneth** [comment]
Hi @archcorsair these native controls are still experimental and aren't working properly for now don't use the nativeControls: true prop and it will use the built in controls of JW

**Comment by et-nat1995** [comment]
@chaimPaneth I am trying to implement a 10 second forward button in the player as well. Are there any updates on this? It has been a few months since the last comment, wondering is anything has changed since then?

I am not using `nativeControls: true` I am using the built in controls.

**Comment by chaimPaneth** [comment]
Hi @et-nat1995 

In the new JWPlayer SDK v4 the player comes with 15 sec rwd / fwd buttons.
